--[[
    TALENTLESS - version SIN KEY (no-key build)
    ------------------------------------------------------------------
    - Ejecuta el MAIN.lua PUBLICO (sin ofuscar) del repositorio, que NO
      contiene ninguna comprobacion de key.
    - Inyecta el catalogo completo de canciones con su metadata
      (nombre, BPM, categorias, alias). Generado por build_nokey.ps1
      a partir de SONGS_META.csv.
    - Neutraliza cualquier peticion al MAIN.lua ofuscado (Luraph)
      redirigiendo la respuesta al MAIN limpio.

    Uso: ejecuta este archivo con tu executor.
    Requiere loadstring + game:HttpGet.
]]

local INCLUDE_ALL_SONGS = true

-- Fuentes del MAIN.lua limpio (se intentan en orden)
local MIRRORS = {
    "https://raw.githubusercontent.com/hellohellohell012321/TALENTLESS/main/MAIN.lua",
    "https://cdn.jsdelivr.net/gh/hellohellohell012321/TALENTLESS@main/MAIN.lua",
    "https://raw.githack.com/hellohellohell012321/TALENTLESS/main/MAIN.lua",
}

local function rawFetch(url)
    local f = game.HttpGet
    if f then
        return f(game, url, true)
    end
    return game:HttpGet(url, true)
end

-- Redirige el MAIN.lua ofuscado al MAIN limpio (sin key).
do
    local orig = game.HttpGet
    if orig then
        local function hook(self, url, ...)
            if type(url) == "string" and url:find("talentless%-raw/MAIN%.lua") then
                local ok, src = pcall(rawFetch, MIRRORS[1])
                if ok and type(src) == "string" and #src > 1000 then
                    return src
                end
            end
            return orig(self, url, ...)
        end
        local ok = pcall(function()
            if newcclosure then
                game.HttpGet = newcclosure(hook)
            else
                game.HttpGet = hook
            end
        end)
        if not ok then
            warn("[TL-NOKEY] No se pudo hookear game.HttpGet (se continua igual).")
        end
    end
end

-- Descarga el MAIN.lua limpio
local source
for _, u in ipairs(MIRRORS) do
    local ok, s = pcall(rawFetch, u)
    if ok and type(s) == "string" and #s > 1000 and s:find("local songs") then
        source = s
        break
    end
end

if not source then
    warn("[TL-NOKEY] No se pudo descargar el MAIN.lua limpio. Revisa tu conexion.")
    return
end

-- Catalogo de canciones.
local SONG_CALLS = [[
    _tl_addsong("2 PHUT HON FUNK", {"phonk", "salesman", "2_PHUT_HON"}, "130", "2_PHUT_HON", {"electronic", "best"})
    _tl_addsong("505", {"arctic monkeys", "artic monkeys", "505"}, "140", "505", {"rock", "sad"})
    _tl_addsong("7 WEEKS & 3 DAYS", {"7_WEEKS_3_DAYS"}, "130", "7_WEEKS_3_DAYS", {"creepy/weirdcore"})
    _tl_addsong("99.9", {"mob psycho 100", "99DOT9"}, "180", "99DOT9", {"anime/jpop", "movies/tv"})
    _tl_addsong("A CRUEL ANGEL'S THESIS", {"neon genesis evangelion", "neo genesis", "a cruel angels", "A_CRUEL_ANGELS_THESIS"}, "76", "A_CRUEL_ANGELS_THESIS", {"movies/tv", "anime/jpop", "best"})
    _tl_addsong("A CYBER'S WORLD?", {"toby fox", "A_CYBERS_WORLD"}, "117", "A_CYBERS_WORLD", {"deltarune", "video games", "best"})
    _tl_addsong("A HOME FOR FLOWERS", {"A_HOME_FOR_FLOWERS"}, "54", "A_HOME_FOR_FLOWERS", {"omori", "video games"})
    _tl_addsong("A SKY FULL OF STARS", {"coldplay", "A_SKY_FULL"}, "120", "A_SKY_FULL", {"epic", "pop/hiphop", "electronic"})
    _tl_addsong("A TALE OF SIX TRILLION YEARS AND A NIGHT", {"Rokuchonen to Ichiya Monogatari", "a tale of six trillion years and a night", "A_TALE_OF_SIX"}, "165", "A_TALE_OF_SIX", {"electronic", "anime/jpop", "movies/tv", "new"})
    _tl_addsong("A THOUSAND MILES", {"popular", "A_THOUSAND"}, "100", "A_THOUSAND", {"pop/hiphop"})
    _tl_addsong("7 YEARS", {"lukas graham", "A7_YEARS"}, "60", "A7_YEARS", {"pop/hiphop", "sad", "best"})
    _tl_addsong("90210", {"travis scott", "A90210"}, "70", "A90210", {"pop/hiphop"})
    _tl_addsong("AFRICA", {"toto", "AFRICA"}, "90", "AFRICA", {"electronic", "memes"})
    _tl_addsong("AFTER DARK", {"mr kitty", "AFTER_DARK"}, "140", "AFTER_DARK", {"sad", "beautiful"})
    _tl_addsong("AI♡SCREAM!", {"aiscream", "ai scream", "AI_SCREAM"}, "135", "AI_SCREAM", {"anime/jpop", "new"})
    _tl_addsong("ALL GIRLS ARE THE SAME", {"juice wrld", "ALL_GIRLS"}, "85", "ALL_GIRLS", {"pop/hiphop", "sad", "best"})
    _tl_addsong("ALL I WANT FOR CHRISTMAS IS YOU", {"mariah carey", "ALL_I_WANT_FOR_CHRISTMAS_IS_YOU"}, "70", "ALL_I_WANT_FOR_CHRISTMAS_IS_YOU", {"pop/hiphop"})
    _tl_addsong("ALL I WANT IS YOU", {"rebzyyx", "ALL_I_WANT_IS_YOU"}, "143", "ALL_I_WANT_IS_YOU", {"pop/hiphop", "sad", "best", "electronic"})
    _tl_addsong("ALL MY FELLAS", {"ALL_MY_FELLAS"}, "160", "ALL_MY_FELLAS", {"memes"})
    _tl_addsong("ALL STAR", {"shrek", "smash mouth", "ALL_STAR"}, "100", "ALL_STAR", {"movies/tv", "memes", "new"})
    _tl_addsong("ALL THE STARS", {"kendrick lamar", "sza", "black panther", "ALL_THE_STARS"}, "120", "ALL_THE_STARS", {"pop/hiphop", "beautiful", "best", "movies/tv"})
    _tl_addsong("ALONE", {"marshmello", "ALONE"}, "142", "ALONE", {"electronic"})
    _tl_addsong("ALORS ON DANSE", {"ALORS_ON_DANSE"}, "120", "ALORS_ON_DANSE", {})
    _tl_addsong("ALTALE", {"ALTALE"}, "90", "ALTALE", {"electronic"})
    _tl_addsong("AMOUR PLASTIQUE", {"napolean", "theres nothing we can do", "videoclub", "AMOUR_PLASTIQUE"}, "120", "AMOUR_PLASTIQUE", {"sad", "memes", "new"})
    _tl_addsong("ANIMATION WARRIOR THEME", {"ANIMATION_WARRIOR_THEME"}, "120", "ANIMATION_WARRIOR_THEME", {})
    _tl_addsong("ANNIHILATE", {"spider man", "spiderman", "spider-man", "metro boomin", "ANNIHILATE"}, "146", "ANNIHILATE", {"pop/hiphop", "movies/tv"})
    _tl_addsong("ANOTHER LOVE", {"sad, love", "ANOTHER_LOVE"}, "123", "ANOTHER_LOVE", {"sad", "best", "epic", "beautiful", "pop/hiphop"})
    _tl_addsong("ANYONE CAN BE FIND LOVE (except you.)", {"breakcore", "ANYONE_CAN"}, "100", "ANYONE_CAN", {"sad"})
    _tl_addsong("AQUATIC AMBIENCE", {"AQUATIC_AMBIENCE"}, "120", "AQUATIC_AMBIENCE", {})
    _tl_addsong("ARIA MATH", {"c418", "ARIA_MATH"}, "84", "ARIA_MATH", {"video games", "minecraft", "beautiful"})
    _tl_addsong("AROUND THE WORLD", {"atc", "la la la", "AROUND_THE_WORLD"}, "121", "AROUND_THE_WORLD", {"electronic", "pop/hiphop", "new"})
    _tl_addsong("ARUARIAN DANCE", {"nujabes", "ARUARIAN"}, "80", "ARUARIAN", {"beautiful"})
    _tl_addsong("AS IT WAS", {"harry styles", "AS_IT_WAS"}, "174", "AS_IT_WAS", {"pop/hiphop", "best"})
    _tl_addsong("ASCENSION", {"ASCENSION"}, "120", "ASCENSION", {})
    _tl_addsong("ASGORE", {"toby fox", "ASGORE"}, "115", "ASGORE", {"video games", "undertale"})
    _tl_addsong("ASSUMPTIONS", {"ASSUMPTIONS"}, "126", "ASSUMPTIONS", {"pop/hiphop", "memes", "electronic"})
    _tl_addsong("ASTRONAMIA (COFFIN DANCE)", {"ASTRONAMIA"}, "120", "ASTRONAMIA", {"memes", "electronic"})
    _tl_addsong("ATTACK OF THE KILLER QUEEN", {"toby fox", "mrbeast", "phonk", "ATTACK_OF_THE_KILLER_QUEEN"}, "144", "ATTACK_OF_THE_KILLER_QUEEN", {"video games", "deltarune", "best"})
    _tl_addsong("AUGUST 10", {"AUGUST_10"}, "120", "AUGUST_10", {})
    _tl_addsong("THE 4 SEASONS - AUTUMN", {"the 4 seasons", "vivaldi", "the four seasons", "AUTUMN"}, "80", "AUTUMN", {"classical"})
    _tl_addsong("AVENGERS (EPIC COVER)", {"movie", "hard", "AVENGERS"}, "120", "AVENGERS", {"epic", "best", "movies/tv"})
    _tl_addsong("BABY", {"BABY"}, "120", "BABY", {})
    _tl_addsong("BABYDOLL", {"BABYDOLL"}, "120", "BABYDOLL", {})
    _tl_addsong("BACK ON TRACK", {"BACK_ON_TRACK"}, "120", "BACK_ON_TRACK", {})
    _tl_addsong("BAD APPLE!!", {"BAD_APPLE"}, "138", "BAD_APPLE", {"anime/jpop"})
    _tl_addsong("BAD HABIT", {"steve lacy", "BAD_HABIT"}, "80", "BAD_HABIT", {"pop/hiphop", "sad"})
    _tl_addsong("BAD PIGGIES", {"angry birds", "BAD_PIGGIES"}, "156", "BAD_PIGGIES", {"video games"})
    _tl_addsong("BARBIE GIRL", {"BARBIE_GIRL"}, "136", "BARBIE_GIRL", {"movies/tv", "memes"})
    _tl_addsong("BASE AFTER BASE", {"BASE_AFTER_BASE"}, "120", "BASE_AFTER_BASE", {})
    _tl_addsong("BATTLE AGAINST A TRUE HERO", {"BATTLE_AGAINST"}, "150", "BATTLE_AGAINST", {"video games", "undertale"})
    _tl_addsong("BEANIE", {"beanie chezile", "BEANIE"}, "135", "BEANIE", {"sad"})
    _tl_addsong("BEAUTIFUL IN WHITE", {"BEAUTIFUL_IN_WHITE"}, "120", "BEAUTIFUL_IN_WHITE", {})
    _tl_addsong("BEAUTIFUL THINGS", {"benson boone", "BEAUTIFUL_THINGS"}, "70", "BEAUTIFUL_THINGS", {"rock", "pop/hiphop"})
    _tl_addsong("BEETHOVEN VIRUS", {"ludwig van beethoven", "BEETHOVEN_VIRUS"}, "162", "BEETHOVEN_VIRUS", {"classical", "electronic", "best", "peak"})
    _tl_addsong("BEGINNING", {"BEGINNING"}, "120", "BEGINNING", {})
    _tl_addsong("BEGINNING 2", {"BEGINNING_2"}, "120", "BEGINNING_2", {})
    _tl_addsong("BELIEVER", {"imagine dragons", "BELIEVER"}, "188", "BELIEVER", {"rock", "pop/hiphop", "epic"})
    _tl_addsong("BELLA CIAO", {"BELLA_CIAO"}, "136", "BELLA_CIAO", {"movies/tv", "best"})
    _tl_addsong("BETTER OFF ALONE", {"a deejay", "deejay", "BETTER_OFF_ALONE"}, "130", "BETTER_OFF_ALONE", {"electronic", "pop/hiphop"})
    _tl_addsong("BIG FISH (大鱼)", {"BIG_FISH"}, "71", "BIG_FISH", {"beautiful"})
    _tl_addsong("BIG SHOT", {"toby fox", "BIG_SHOT"}, "280", "BIG_SHOT", {"deltarune", "video games"})
    _tl_addsong("BINKS RUM", {"BINKS_RUM"}, "120", "BINKS_RUM", {})
    _tl_addsong("BIRDLAND", {"jazz", "BIRDLAND"}, "155", "BIRDLAND", {"new"})
    _tl_addsong("BIRDS OF A FEATHER", {"billie eilish", "BIRDS_OF_A"}, "105", "BIRDS_OF_A", {"pop/hiphop", "beautiful"})
    _tl_addsong("BLACK CATCHER", {"black clover", "BLACK_CATCHER"}, "88", "BLACK_CATCHER", {"anime/jpop", "movies/tv"})
    _tl_addsong("BLACK KNIFE", {"toby fox", "BLACK_KNIFE"}, "148", "BLACK_KNIFE", {"deltarune", "video games"})
    _tl_addsong("BLIND SPOTS", {"BLIND_SPOTS"}, "120", "BLIND_SPOTS", {})
    _tl_addsong("BLIND SPOTS 2", {"BLIND_SPOTS_2"}, "120", "BLIND_SPOTS_2", {})
    _tl_addsong("BLINDING LIGHTS", {"the weeknd", "BLINDING_LIGHTS"}, "171", "BLINDING_LIGHTS", {"pop/hiphop", "best"})
    _tl_addsong("BLOODY MARY", {"lady gaga", "wednesday", "BLOODY"}, "100", "BLOODY", {"pop/hiphop", "epic", "best"})
    _tl_addsong("BLUE (DA BA DEE)", {"im blue", "im good", "BLUE"}, "130", "BLUE", {"pop/hiphop"})
    _tl_addsong("BLUE (YUNG KAI)", {"BLUE_YUNG"}, "92", "BLUE_YUNG", {"beautiful", "best"})
    _tl_addsong("BLUE BIRD", {"naruto shippuden", "BLUEBIRD"}, "145", "BLUEBIRD", {"anime/jpop", "movies/tv"})
    _tl_addsong("BOHEMIAN RHAPSODY", {"queen", "BOHEMIAN_RHAPSODY"}, "80", "BOHEMIAN_RHAPSODY", {"rock"})
    _tl_addsong("BOOM BOOM BOOM BOOM", {"vengaboys", "BOOM_BOOM_BOOM_BOOM"}, "120", "BOOM_BOOM_BOOM_BOOM", {"pop/hiphop", "memes"})
    _tl_addsong("BREADY, SET, GO!", {"BREADY"}, "160", "BREADY", {"video games", "omori", "best"})
    _tl_addsong("BUTCHER VANITY", {"vane lily", "forsaken", "roblox", "BUTCHER_VANITY"}, "142", "BUTCHER_VANITY", {"video games"})
    _tl_addsong("BY YOUR SIDE", {"BY_YOUR_SIDE"}, "88", "BY_YOUR_SIDE", {"video games", "omori"})
    _tl_addsong("CALL ME MAYBE", {"CALL_ME_MAYBE"}, "120", "CALL_ME_MAYBE", {})
    _tl_addsong("CALL OF SILENCE", {"CALL_OF_SILENCE"}, "120", "CALL_OF_SILENCE", {})
    _tl_addsong("CALL OUT MY NAME", {"the weeknd", "CALL_OUT_MY_NAME"}, "67", "CALL_OUT_MY_NAME", {"pop/hiphop", "new"})
    _tl_addsong("CAN YOU HEAR THE MUSIC (EPIC VER.)", {"hans zimmer", "oppenheimer", "CAN_YOU_HEAR_EPIC"}, "102", "CAN_YOU_HEAR_EPIC", {"epic", "best", "peak", "movies/tv"})
    _tl_addsong("CAN YOU HEAR THE MUSIC", {"oppenheimer", "popular", "CAN_YOU_HEAR_THE_FUCKING_MUSIC"}, "80", "CAN_YOU_HEAR_THE_FUCKING_MUSIC", {"epic", "movies/tv"})
    _tl_addsong("CANDYLAND", {"tobu", "ncs", "no copyright sounds", "CANDYLAND"}, "130", "CANDYLAND", {"electronic", "best", "best"})
    _tl_addsong("CANON IN D", {"CANON_D"}, "100", "CANON_D", {"classical"})
    _tl_addsong("CAN'T HELP FALLING IN LOVE", {"elvis presley", "cant help falling in love", "CANT_HELP_FALLING_IN_LOVE"}, "120", "CANT_HELP_FALLING_IN_LOVE", {})
    _tl_addsong("CANT LET GO", {"geometry dash", "gd", "CANT_LET"}, "160", "CANT_LET", {"video games", "electronic"})
    _tl_addsong("CARAMELLDANSEN", {"CARAMELLDANSEN"}, "120", "CARAMELLDANSEN", {})
    _tl_addsong("CARELESS WHISPER", {"CARELESS"}, "153", "CARELESS", {"memes"})
    _tl_addsong("CAROL OF THE BELLS", {"christmas", "CAROL_OF_THE_BELLS"}, "50", "CAROL_OF_THE_BELLS", {"classical", "beautiful", "best"})
    _tl_addsong("CAROL OF THE BELLS (EPIC VER.)", {"christmas", "peter buka", "CAROL_OF_THE_BELLS_EPIC"}, "135", "CAROL_OF_THE_BELLS_EPIC", {"classical", "epic", "beautiful", "best"})
    _tl_addsong("CENTIMETER", {"rent a girlfriend", "rent-a-girlfriend", "CENTIMETER"}, "140", "CENTIMETER", {"anime/jpop", "movies/tv"})
    _tl_addsong("CHA-LA HEAD-CHA-LA", {"dragon ball z", "CHA_LA_HEAD_CHA_LA"}, "154", "CHA_LA_HEAD_CHA_LA", {"anime/jpop", "movies/tv", "best"})
    _tl_addsong("CHAMBER OF REFLECTION", {"mac demarco", "CHAMBER_OF_REFLECTION"}, "128", "CHAMBER_OF_REFLECTION", {"sad", "beautiful", "best"})
    _tl_addsong("CHAMPAGNE COAST", {"CHAMPAGNE_COAST"}, "120", "CHAMPAGNE_COAST", {})
    _tl_addsong("CHAOS KING", {"toby fox", "CHAOS_KING"}, "148", "CHAOS_KING", {"deltarune", "video games"})
    _tl_addsong("CHARIOTS OF FIRE", {"CHARIOTS_OF_FIRE"}, "120", "CHARIOTS_OF_FIRE", {})
    _tl_addsong("CHIISANA KOI NO UTA", {"CHIISANA_KOI_NO_UTA"}, "100", "CHIISANA_KOI_NO_UTA", {"anime/jpop", "movies/tv", "best"})
    _tl_addsong("CHILDREN", {"robert miles", "CHILDREN"}, "137", "CHILDREN", {"electronic", "sad", "best", "new"})
    _tl_addsong("CHRISTMAS KIDS", {"roar", "CHRISTMAS_KIDS"}, "152", "CHRISTMAS_KIDS", {"sad"})
    _tl_addsong("CLAIR DE LUNE", {"debussy", "CLAIR_DE_LUNE"}, "48", "CLAIR_DE_LUNE", {"classical", "beautiful"})
    _tl_addsong("CLOCKS", {"coldplay", "CLOCKS"}, "132", "CLOCKS", {"rock"})
    _tl_addsong("CLOSE EYES", {"closed eyes", "dvrst", "phonk", "CLOSE_EYES"}, "114", "CLOSE_EYES", {"electronic"})
    _tl_addsong("CLOUD 9", {"tobu", "ncs", "no copyright sounds", "CLOUD_9"}, "128", "CLOUD_9", {"electronic"})
    _tl_addsong("CLUBSTEP", {"geometry dash", "dj nate", "gd", "CLUBSTEP"}, "128", "CLUBSTEP", {"video games", "electronic"})
    _tl_addsong("COCONUT MALL !!", {"mario kart", "nintendo", "COCONUT"}, "132", "COCONUT", {"video games"})
    _tl_addsong("COMEDY", {"COMEDY"}, "88", "COMEDY", {"movies/tv", "anime/jpop"})
    _tl_addsong("COMPTINE D'UN AUTRE ÉTÉ", {"yann tiersen", "amelie", "COMPTINE_DUN_AUTRE_ETE"}, "95", "COMPTINE_DUN_AUTRE_ETE", {"classical", "beautiful"})
    _tl_addsong("RACHMANINOFF - CONCERTO OP.30 NO.3", {"rachmaninoff", "CONCERTO_OP30_NO3"}, "150", "CONCERTO_OP30_NO3", {"classical"})
    _tl_addsong("CONGRATULATIONS", {"mac miller", "CONGRATULATIONS"}, "60", "CONGRATULATIONS", {"beautiful", "sad", "new"})
    _tl_addsong("CORNFIELD CHASE", {"CORNFIELD_CHASE"}, "120", "CORNFIELD_CHASE", {})
    _tl_addsong("COUNTING STARS", {"one republic", "COUNTING_STARS"}, "105", "COUNTING_STARS", {"pop/hiphop", "sad"})
    _tl_addsong("CRAB RAVE", {"no copyright sounds", "ncs", "noisestorm", "CRAB_RAVE"}, "125", "CRAB_RAVE", {"memes", "electronic", "epic"})
    _tl_addsong("CRADLES", {"ncs", "no copyright sounds", "sub urban", "CRADLES"}, "158", "CRADLES", {"electronic"})
    _tl_addsong("CRAZY FROG", {"axel f", "CRAZY_FROG"}, "130", "CRAZY_FROG", {"memes", "electronic"})
    _tl_addsong("CREEP", {"radiohead", "CREEP"}, "100", "CREEP", {"rock", "sad"})
    _tl_addsong("CREEPIN'", {"metro boomin", "the weeknd", "21 savage", "CREEPIN"}, "98", "CREEPIN", {"pop/hiphop", "best", "new"})
    _tl_addsong("CROSSING FIELD", {"sword art online", "sao", "CROSSING_FIELD"}, "179", "CROSSING_FIELD", {"anime/jpop", "movies/tv"})
    _tl_addsong("CRUCIFIED", {"army of lovers", "CRUCIFIED"}, "144", "CRUCIFIED", {"pop/hiphop"})
    _tl_addsong("CRY FOR ME (feat. 愛海)", {"CRY_FOR_ME_MICHITA"}, "92", "CRY_FOR_ME_MICHITA", {"beautiful", "sad"})
    _tl_addsong("CUPID", {"love", "CUPID"}, "120", "CUPID", {"pop/hiphop"})
    _tl_addsong("CUTE DEPRESSED", {"CUTE_DEPRESSED"}, "130", "CUTE_DEPRESSED", {"memes", "best"})
    _tl_addsong("CYCLES", {"CYCLES"}, "120", "CYCLES", {})
    _tl_addsong("DAD BATTLE (FNF)", {"friday night funkin", "kawai sprite", "DAD_BATTLE"}, "180", "DAD_BATTLE", {"video games", "new"})
    _tl_addsong("DAIJOUBU", {"DAIJOUBU"}, "120", "DAIJOUBU", {})
    _tl_addsong("DAISY BELL", {"DAISY_BELL"}, "120", "DAISY_BELL", {"creepy/weirdcore"})
    _tl_addsong("DAMNED (COD ZOMBIES)", {"cod zombies theme", "call of duty", "creepy", "DAMNED"}, "95", "DAMNED", {"video games"})
    _tl_addsong("DANDELIONS", {"DANDELIONS"}, "100", "DANDELIONS", {})
    _tl_addsong("DARK BEACH", {"pastel ghost", "DARK_BEACH"}, "130", "DARK_BEACH", {"sad", "beautiful"})
    _tl_addsong("DARK IS THE NIGHT", {"Nikita Bogoslovsky", "DARK_IS_THE_NIGHT"}, "120", "DARK_IS_THE_NIGHT", {"sad"})
    _tl_addsong("DAWN OF THE DOORS", {"doors", "roblox", "lsplash", "DAWN_OF"}, "72", "DAWN_OF", {"video games"})
    _tl_addsong("DAYLIGHT", {"david kushner", "DAYLIGHT"}, "130", "DAYLIGHT", {"beautiful", "epic", "best"})
    _tl_addsong("DEADLOCKED", {"geometry dash", "gd", "DEADLOCKED"}, "140", "DEADLOCKED", {"video games", "electronic"})
    _tl_addsong("DEATH BED", {"powfu", "beabadoobee", "DEATH_BED"}, "120", "DEATH_BED", {"pop/hiphop", "sad", "beautiful"})
    _tl_addsong("DEATH WALTZ (WARNING)", {"DEATH_WALTZ"}, "210", "DEATH_WALTZ", {"all"})
    _tl_addsong("DECK THE HALLS", {"DECK_THE_HALLS"}, "120", "DECK_THE_HALLS", {})
    _tl_addsong("DEPARTURE!", {"hunter x hunter", "DEPARTURE"}, "150", "DEPARTURE", {"movies/tv", "anime/jpop"})
    _tl_addsong("DESPACITO", {"DESPACITO"}, "89", "DESPACITO", {"pop/hiphop", "memes"})
    _tl_addsong("DETROIT: BECOME HUMAN - OPENING", {"DETROIT"}, "60", "DETROIT", {"video games", "beautiful"})
    _tl_addsong("DEXTER - BLOOD THEME", {"DEXTER_BLOOD_THEME"}, "82", "DEXTER_BLOOD_THEME", {"movies/tv"})
    _tl_addsong("DIE FOR YOU", {"the weeknd", "DIE_FOR_YOU"}, "66", "DIE_FOR_YOU", {"pop/hiphop", "best", "new"})
    _tl_addsong("DIES IRAE (REQUIEM MVT.3)", {"mozart", "DIE_IRAE_III"}, "160", "DIE_IRAE_III", {"classical"})
    _tl_addsong("DIE WITH A SMILE", {"lady gaga", "bruno mars", "DIE_WITH"}, "76", "DIE_WITH", {"pop/hiphop", "sad", "beautiful", "best", "peak"})
    _tl_addsong("DIED IN YOUR ARMS", {"DIED_IN_YOUR_ARMS"}, "120", "DIED_IN_YOUR_ARMS", {})
    _tl_addsong("DIES IRAE (MESSA DA REQUIEM)", {"giuseppe verdi", "DIES_IRAE"}, "160", "DIES_IRAE", {"classical", "best", "peak", "epic"})
    _tl_addsong("DIES IRAE (REQUIEM MVT.3) (EPIC VER.)", {"mozart", "epic", "DIES_IRAE_III_2"}, "160", "DIES_IRAE_III_2", {"classical", "epic", "best", "peak"})
    _tl_addsong("DIRTMOUTH", {"hollow knight", "DIRTMOUTH"}, "87", "DIRTMOUTH", {"video games", "new"})
    _tl_addsong("DOG SONG", {"DOG_SONG"}, "230", "DOG_SONG", {"video games", "undertale"})
    _tl_addsong("DOKI DOKI LITERATURE CLUB", {"DOKI_DOKI_LITERATURE_CLUB"}, "120", "DOKI_DOKI_LITERATURE_CLUB", {})
    _tl_addsong("DONT STOP BELIEVIN'", {"journey", "DONT_STOP"}, "118", "DONT_STOP", {"rock", "best"})
    _tl_addsong("DRAGOSTEA DIN TEI (NUMA NUMA)", {"o-zone", "o zone", "DRAGOSTEA_DIN_TEI"}, "130", "DRAGOSTEA_DIN_TEI", {"pop/hiphop", "electronic", "memes"})
    _tl_addsong("DRAMAMIME", {"flawed mangoes", "DRAMAM"}, "224", "DRAMAM", {"beautiful"})
    _tl_addsong("DREAM FLOWER", {"klydix", "DREAM_FL"}, "150", "DREAM_FL", {"electronic"})
    _tl_addsong("DREAM LANTERN", {"DREAM_LANTERN"}, "120", "DREAM_LANTERN", {})
    _tl_addsong("DREAM ON", {"aerosmith", "DREAM_ON"}, "78", "DREAM_ON", {"rock"})
    _tl_addsong("DREITON BEST PART", {"DREITON_BEST_PART"}, "120", "DREITON_BEST_PART", {})
    _tl_addsong("DROWNING LOVE", {"chasing kou", "DROWNING_LOVE"}, "112", "DROWNING_LOVE", {"beautiful", "sad", "best", "peak", "movies/tv"})
    _tl_addsong("DRY HANDS", {"c418", "DRY_HANDS"}, "90", "DRY_HANDS", {"video games", "minecraft", "beautiful"})
    _tl_addsong("DRY OUT", {"DRY_OUT"}, "120", "DRY_OUT", {})
    _tl_addsong("DUMB DUMB", {"everyone is dumb", "DUMB_DUMB"}, "118", "DUMB_DUMB", {"memes"})
    _tl_addsong("DUVET", {"boa", "DUVET"}, "91", "DUVET", {"sad", "beautiful", "best"})
    _tl_addsong("EASY ON ME", {"adele", "EASY_ON_ME"}, "73", "EASY_ON_ME", {"pop/hiphop"})
    _tl_addsong("ELEVATOR JAM", {"doors", "roblox", "lsplash", "ELEVATOR_JAM"}, "146", "ELEVATOR_JAM", {"video games"})
    _tl_addsong("ELEVATOR JAM x HERE I COME", {"doors", "roblox", "lsplash", "ELEVATOR_JAM_2"}, "146", "ELEVATOR_JAM_2", {"video games", "epic", "best"})
    _tl_addsong("ENEMY", {"imagine dragons", "arcane", "ENEMY"}, "77", "ENEMY", {"pop/hiphop"})
    _tl_addsong("ENGRAVINGS", {"ENGRAVINGS"}, "120", "ENGRAVINGS", {})
    _tl_addsong("AN ENIGMATIC ENCOUNTER", {"undertale last breath", "toby fox", "ENIGMATIC"}, "50", "ENIGMATIC", {"video games", "undertale", "best", "peak"})
    _tl_addsong("ENTRY OF THE GLADIATORS", {"circus", "clown", "ENTRY_OF_THE"}, "220", "ENTRY_OF_THE", {"classical", "memes"})
    _tl_addsong("ERIKA", {"nazi", "hitler", "german", "ww2", "world war 2", "ERIKA"}, "120", "ERIKA", {"memes"})
    _tl_addsong("ETHEREAL", {"txmy", "ETHEREAL"}, "132", "ETHEREAL", {"beautiful", "best", "peak"})
    _tl_addsong("LISZT - ETUDE NO.3 (UN SOSPIRO)", {"franz liszt", "ETUDE_NO3_UN_SOSPIRO"}, "25", "ETUDE_NO3_UN_SOSPIRO", {"classical"})
    _tl_addsong("EVERGREEN", {"EVERGREEN"}, "120", "EVERGREEN", {"beautiful", "best"})
    _tl_addsong("EVERY LIVING BREATHING", {"EVERY_LIVING_BREATHING"}, "120", "EVERY_LIVING_BREATHING", {})
    _tl_addsong("EXPERIENCE", {"EXPERIENCE"}, "92", "EXPERIENCE", {"epic", "best", "beautiful", "peak"})
    _tl_addsong("EXPERIENCE FLOWS IN YOU", {"tony ann", "river flows in you", "EXPERIENCE_FLOWS"}, "85", "EXPERIENCE_FLOWS", {"beautiful", "best"})
    _tl_addsong("f", {"f"}, "120", "f", {})
    _tl_addsong("F1", {"hans zimmer", "F1"}, "110", "F1", {"movies/tv"})
    _tl_addsong("FADED", {"ncs", "alan walker", "no copyright sounds", "FADED"}, "90", "FADED", {"electronic", "sad"})
    _tl_addsong("FALLEN DOWN", {"FALLEN_DOWN"}, "110", "FALLEN_DOWN", {"video games", "undertale", "beautiful"})
    _tl_addsong("FANTAISIE IMPROMPTU", {"frederic chopin", "FANTAISIE"}, "168", "FANTAISIE", {"classical"})
    _tl_addsong("FAST", {"juice wrld", "FAST"}, "86", "FAST", {"pop/hiphop", "sad"})
    _tl_addsong("FEEL GOOD INC", {"gorillaz", "FEEL_GOOD_INC"}, "100", "FEEL_GOOD_INC", {"pop/hiphop", "rock", "best", "new"})
    _tl_addsong("FIELD OF HOPES AND DREAMS", {"toby fox", "FIELD_OF_HOPES_AND_DREAMS"}, "125", "FIELD_OF_HOPES_AND_DREAMS", {"deltarune", "video games"})
    _tl_addsong("FIELD OF MEMORIES", {"waterflame", "stick war", "FIELD_OF_MEMORIES"}, "130", "FIELD_OF_MEMORIES", {"video games", "electronic", "epic"})
    _tl_addsong("FINAL DUET", {"omori", "FINAL_DUET"}, "84", "FINAL_DUET", {"video games", "omori"})
    _tl_addsong("FINALE", {"toby fox", "flowey", "FINALE"}, "190", "FINALE", {"video games", "undertale"})
    _tl_addsong("FIREWORKS", {"FIREWORKS"}, "120", "FIREWORKS", {})
    _tl_addsong("FIVE NIGHTS AT FREDDYS 1", {"fnaf", "five nights at freddys", "the living tombstone", "FIVE_NIGHTS_1"}, "108", "FIVE_NIGHTS_1", {"video games", "electronic", "epic"})
    _tl_addsong("FLARE", {"hensonn", "sahara", "phonk", "FLARE"}, "150", "FLARE", {"electronic"})
    _tl_addsong("FLASHING LIGHTS", {"kanye west", "graduation", "FLASHING"}, "100", "FLASHING", {"pop/hiphop", "epic", "beautiful"})
    _tl_addsong("FLIGHT (MAN OF STEEL)", {"hans zimmer", "FLIGHT"}, "80", "FLIGHT", {"movies/tv", "new"})
    _tl_addsong("FLIGHT OF THE BUMBLEBEE", {"FLIGHT_OF_THE_BUMBLEBEE"}, "175", "FLIGHT_OF_THE_BUMBLEBEE", {"peak", "best"})
    _tl_addsong("FLOWER DANCE", {"FLOWER_DANCE"}, "120", "FLOWER_DANCE", {})
    _tl_addsong("FLUXXWAVE", {"FLUXXWAVE"}, "120", "FLUXXWAVE", {})
    _tl_addsong("FLY ME TO THE MOON", {"frank sinatra", "love", "squid game", "jazz", "FLY_ME_TO_THE_MOON"}, "140", "FLY_ME_TO_THE_MOON", {"classical", "beautiful"})
    _tl_addsong("FLY, MY WINGS", {"limbus company", "mili", "fly my wings", "FLY_MY_WINGS"}, "72", "FLY_MY_WINGS", {"video games", "new"})
    _tl_addsong("FOR THE DAMAGED CODA", {"evil morty", "rick and morty", "rick & morty", "FOR_THE_DAMAGED_CODA"}, "140", "FOR_THE_DAMAGED_CODA", {"sad", "memes", "epic"})
    _tl_addsong("FOR THE DAMAGED CODA (EPIC VER.)", {"evil morty", "rick and morty", "rick & morty", "FOR_THE_DAMAGED_CODA_2"}, "150", "FOR_THE_DAMAGED_CODA_2", {"sad", "memes", "epic", "best", "peak"})
    _tl_addsong("FROM THE START", {"laufey", "love", "popular", "FR"}, "82", "FR", {"beautiful"})
    _tl_addsong("FREAKS", {"surf curse", "FREAKS"}, "175", "FREAKS", {"sad", "rock", "beautiful"})
    _tl_addsong("FREEDOM DIVE", {"xi", "FREEDOM_DIVE"}, "220", "FREEDOM_DIVE", {"electronic"})
    _tl_addsong("FRIENDS", {"marshmello", "anne marie", "FRIENDS"}, "95", "FRIENDS", {"pop/hiphop", "electronic"})
    _tl_addsong("FUKASHIGI NO CARTE", {"senpai", "FUKASHIGI"}, "90", "FUKASHIGI", {"anime/jpop", "movies/tv"})
    _tl_addsong("FUNK ESTRANHO", {"ALXIKE", "phonk", "FUNK_ESTRANHO"}, "111", "FUNK_ESTRANHO", {"electronic"})
    _tl_addsong("FUR ELISE", {"ludwig van beethoven", "classical", "FUR_ELISE"}, "72", "FUR_ELISE", {"classical"})
    _tl_addsong("GANGSTA'S PARADISE", {"coolio", "GANGSTAS_PARADISE"}, "80", "GANGSTAS_PARADISE", {"pop/hiphop", "memes", "beautiful", "best", "epic", "peak"})
    _tl_addsong("GEOMETRICAL DOMINATOR", {"geometry dash", "gd", "waterflame", "GEOMETRICAL_DOMINATOR"}, "80", "GEOMETRICAL_DOMINATOR", {"video games", "electronic", "new"})
    _tl_addsong("GEOMETRY DASH THEME (DASH)", {"geometry dash", "gd", "GEOMETRY_DASH"}, "128", "GEOMETRY_DASH", {"video games", "electronic"})
    _tl_addsong("GIGACHAD THEME", {"GIGACHAD_THEME"}, "120", "GIGACHAD_THEME", {})
    _tl_addsong("GIMME! GIMME! GIMME!", {"abba", "GIMME_GIMME_GIMME"}, "116", "GIMME_GIMME_GIMME", {"pop/hiphop"})
    _tl_addsong("GIORNO'S THEME", {"giornos theme", "jojo", "jojo's bizarre adventure", "GIORNO"}, "135", "GIORNO", {"anime/jpop", "memes", "movies/tv"})
    _tl_addsong("NEVER GONNA GIVE YOU UP", {"rick astley", "rickroll", "rick roll", "GIVE_UP"}, "113", "GIVE_UP", {"memes", "pop/hiphop"})
    _tl_addsong("GLASSY SKY", {"tokyo ghoul", "GLASSY_SKY"}, "68", "GLASSY_SKY", {"anime/jpop", "sad", "movies/tv"})
    _tl_addsong("GODS PLAN", {"drake", "GODS_PLAN"}, "130", "GODS_PLAN", {"pop/hiphop"})
    _tl_addsong("GOLDEN BROWN", {"the stranglers", "GOLDEN_BROW"}, "94", "GOLDEN_BROW", {"rock", "new"})
    _tl_addsong("GOLDEN HOUR", {"jvke", "love, sad", "popular", "GOLDEN_HOUR"}, "94", "GOLDEN_HOUR", {"beautiful", "best"})
    _tl_addsong("GONE ANGELS", {"limbus company", "mili", "GONE_ANGELS"}, "188", "GONE_ANGELS", {"video games", "new"})
    _tl_addsong("GOOD MORNING (OMORI)", {"omori", "GOOD_MORNING"}, "90", "GOOD_MORNING", {"video games", "omori"})
    _tl_addsong("GOOFY AHH NPC MUSIC", {"whistle", "GOOFY_AHH"}, "120", "GOOFY_AHH", {"memes", "epic", "best", "beautiful", "peak"})
    _tl_addsong("GRAVITY FALLS", {"GRAVITY_FALLS"}, "120", "GRAVITY_FALLS", {"memes", "best", "movies/tv"})
    _tl_addsong("GUREN NO YUMIYA", {"animenz", "attack on titan", "aot", "GUREN_NO_YUMIYA"}, "176", "GUREN_NO_YUMIYA", {"movies/tv", "anime/jpop", "epic"})
    _tl_addsong("GURENGE", {"lisa", "demon slayer", "GURENGE"}, "135", "GURENGE", {"anime/jpop", "movies/tv", "best", "epic", "beautiful", "peak"})
    _tl_addsong("GYMNOPÉDIE NO.1", {"satie", "GYMNOPEDIE_NO1"}, "54", "GYMNOPEDIE_NO1", {"classical"})
    _tl_addsong("GYMNOPÉDIE NO.3", {"satie", "GYMNOPEDIE_NO3"}, "48", "GYMNOPEDIE_NO3", {"classical"})
    _tl_addsong("GYMNOPÉDIE NO.2", {"satie", "GYMONPEDIE_NO2"}, "48", "GYMONPEDIE_NO2", {"classical"})
    _tl_addsong("GYPSY WOMAN", {"crystal waters", "slickback", "slick back", "gipsy woman", "GYPSY_WOMAN"}, "120", "GYPSY_WOMAN", {"memes", "pop/hiphop"})
    _tl_addsong("HAGGSTORM", {"c418", "HAGGSTORM"}, "102", "HAGGSTORM", {"video games", "minecraft"})
    _tl_addsong("HANA NI NATTE", {"the apothecary diaries", "HANA_NI_NATTE"}, "200", "HANA_NI_NATTE", {"anime/jpop", "movies/tv"})
    _tl_addsong("HAPPIER", {"marshmello", "bastille", "HAPPIER"}, "100", "HAPPIER", {"pop/hiphop", "sad", "beautiful", "best"})
    _tl_addsong("HATSUNE MIKU NO GEKISHOU (激唱)", {"hatsune miku", "vocaloid", "miku", "colorful stage", "project sekai", "HATSUNE_MIKU_NO_GEKISHOU"}, "200", "HATSUNE_MIKU_NO_GEKISHOU", {"anime/jpop", "best", "epic"})
    _tl_addsong("HAZY MOON", {"minato", "hatsune miku", "HAZY_MOON"}, "120", "HAZY_MOON", {"anime/jpop", "beautiful"})
    _tl_addsong("HEART AFIRE", {"defqwop", "HEART_AFIRE"}, "100", "HEART_AFIRE", {"epic", "beautiful", "best"})
    _tl_addsong("HEARTACHE", {"HEARTACHE"}, "160", "HEARTACHE", {"video games", "undertale"})
    _tl_addsong("HEAT WAVE", {"glass animals", "HEAT_WAVE"}, "81", "HEAT_WAVE", {"pop/hiphop"})
    _tl_addsong("HEATHENS", {"twenty one pilots", "suicide squad", "HEATHENS"}, "90", "HEATHENS", {"sad"})
    _tl_addsong("HELLO X I LOVE YOU", {"omfg", "HELLO"}, "105", "HELLO", {"electronic"})
    _tl_addsong("HELLO (ADELE)", {"adele", "HELLO_ADELE"}, "85", "HELLO_ADELE", {"pop/hiphop"})
    _tl_addsong("HER JVKE", {"HER_JVKE"}, "120", "HER_JVKE", {})
    _tl_addsong("HERE I COME", {"doors", "roblox", "lsplash", "HERE_I_COME"}, "144", "HERE_I_COME", {"video games"})
    _tl_addsong("HERE TO STAY", {"HERE_TO_STAY"}, "120", "HERE_TO_STAY", {})
    _tl_addsong("HERO (LIMBUS COMPANY)", {"mili", "HERO"}, "220", "HERO", {"video games", "best", "new"})
    _tl_addsong("HES A PIRATE", {"hans zimmer", "pirates of the caribbean", "HES_A_PIRATE"}, "207", "HES_A_PIRATE", {"epic", "best", "movies/tv"})
    _tl_addsong("HEY KIDS", {"HEY_KIDS"}, "87", "HEY_KIDS", {"creepy/weirdcore"})
    _tl_addsong("HH", {"kanye west", "heil hitler", "HH"}, "150", "HH", {"memes", "peak"})
    _tl_addsong("HIDE", {"dorian concept", "hide dorian concept", "HIDE"}, "100", "HIDE", {"beautiful", "new"})
    _tl_addsong("HIGH HOPES", {"panic at the disco", "panic!", "house of memories", "HIGH_HOPES"}, "164", "HIGH_HOPES", {"pop/hiphop", "epic"})
    _tl_addsong("HIMITSU KOI GOKORO", {"rent a girlfriend", "rent-a-girlfriend", "honeyworks", "HIMITSU_KOI_GOKORO"}, "165", "HIMITSU_KOI_GOKORO", {"anime/jpop", "movies/tv"})
    _tl_addsong("HIS THEME", {"HIS_THEME"}, "90", "HIS_THEME", {"video games", "undertale"})
    _tl_addsong("HIT THE ROAD, JACK", {"shake", "HIT_THE_ROAD"}, "60", "HIT_THE_ROAD", {"rock"})
    _tl_addsong("HOLLOW KNIGHT MAIN THEME", {"HOLLOW_KNIGHT_MAIN_THEME"}, "55", "HOLLOW_KNIGHT_MAIN_THEME", {"video games", "new"})
    _tl_addsong("HOME (UNDERTALE)", {"toby fox", "HOME"}, "115", "HOME", {"undertale", "video games", "new"})
    _tl_addsong("HOMELANDER MASHUP", {"HOMELANDER_MASHUP"}, "120", "HOMELANDER_MASHUP", {})
    _tl_addsong("HOPE", {"xxxtentacion", "HOPE"}, "146", "HOPE", {"pop/hiphop", "sad", "beautiful", "best"})
    _tl_addsong("HOPES AND DREAMS", {"asriel", "HOPES_DREAMS"}, "170", "HOPES_DREAMS", {"video games", "undertale", "best", "epic", "peak"})
    _tl_addsong("HOTLINE BLING", {"drake", "HOTLINE_BLING"}, "100", "HOTLINE_BLING", {"pop/hiphop"})
    _tl_addsong("HOUSE OF MEMORIES", {"panic at the disco", "panic!", "high hopes", "HOUSE_OF"}, "112", "HOUSE_OF", {"pop/hiphop"})
    _tl_addsong("MERRY-GO-ROUND OF LIFE", {"howls moving castle", "howl's moving castle", "merry-go-round", "ghibli", "HOWLS_MOVING_CASTLE"}, "156", "HOWLS_MOVING_CASTLE", {"anime/jpop", "beautiful", "movies/tv"})
    _tl_addsong("MERRY-GO-ROUND OF LIFE", {"howls moving castle", "howl's moving castle", "merry-go-round", "ghibli", "HOWLS_MOVING_CASTLE_2"}, "130", "HOWLS_MOVING_CASTLE_2", {"anime/jpop", "beautiful", "best", "epic", "peak", "movies/tv"})
    _tl_addsong("HUNGARIAN DANCE", {"HUNGARIAN"}, "130", "HUNGARIAN", {"classical"})
    _tl_addsong("I BROKE A STRING MAKING THIS PART", {"I_BROKE_A_STRING"}, "120", "I_BROKE_A_STRING", {"beautiful", "best", "epic"})
    _tl_addsong("I CANT HANDLE CHANGE", {"roar", "I_CANT_HANDLE_CHANGE"}, "120", "I_CANT_HANDLE_CHANGE", {"sad", "rock"})
    _tl_addsong("I HATE U I LOVE U", {"I_HATE_U_I_LOVE_U"}, "120", "I_HATE_U_I_LOVE_U", {})
    _tl_addsong("I LIKE THE WAY YOU KISS ME", {"artemis", "I_LIKE_THE_WAY_YOU"}, "151", "I_LIKE_THE_WAY_YOU", {"pop/hiphop", "sad", "best", "beautiful"})
    _tl_addsong("I REALLY WANT TO STAY AT YOUR HOUSE", {"cyberpunk", "I_REALLY_WANT_TO_STAY"}, "128", "I_REALLY_WANT_TO_STAY", {"movies/tv", "pop/hiphop", "beautiful", "electronic"})
    _tl_addsong("I STILL LOVE YOU", {"I_STILL_LOVE_YOU"}, "120", "I_STILL_LOVE_YOU", {})
    _tl_addsong("I WANT IT THAT WAY", {"backstreet boys", "I_WANT"}, "122", "I_WANT", {"pop/hiphop", "rock"})
    _tl_addsong("I WANT YOU TO TELL ME", {"I_WANT_YOU_TO_TELL_ME"}, "120", "I_WANT_YOU_TO_TELL_ME", {})
    _tl_addsong("I WONDER", {"kanye west", "graduation", "I_WONDER"}, "90", "I_WONDER", {"pop/hiphop", "beautiful"})
    _tl_addsong("ICARUS", {"tony ann", "ICARUS"}, "100", "ICARUS", {"beautiful"})
    _tl_addsong("IDEA 1", {"gibran alcocer", "IDEA_1"}, "160", "IDEA_1", {"classical"})
    _tl_addsong("IDEA 10", {"gibran alcocers", "IDEA_10"}, "170", "IDEA_10", {"beautiful"})
    _tl_addsong("IDEA 22", {"gibran alcocer", "IDEA_22"}, "120", "IDEA_22", {"classical"})
    _tl_addsong("IDEA 9", {"gibran alcocer", "IDEA_9"}, "195", "IDEA_9", {"classical"})
    _tl_addsong("IDGAF", {"boywithuke", "blackbear", "IDGAF"}, "196", "IDGAF", {"sad"})
    _tl_addsong("IDOL", {"oshi no ko", "yoasobi", "IDOL"}, "166", "IDOL", {"anime/jpop", "best", "movies/tv"})
    _tl_addsong("IDOL (EPIC VER.)", {"oshi no ko", "yoasobi", "IDOL_EPIC"}, "166", "IDOL_EPIC", {"anime/jpop", "epic", "best", "movies/tv"})
    _tl_addsong("IF I AM WITH YOU", {"jjk", "jujutsu kaisen", "hollow purple", "the honored one", "gojo satoru", "premature death", "IF_I_AM_WITH_YOU"}, "82", "IF_I_AM_WITH_YOU", {"anime/jpop", "best", "beautiful", "peak", "movies/tv"})
    _tl_addsong("ILLUSIONARY DAYTIME", {"ILLUSIONARY_DAYTIME"}, "120", "ILLUSIONARY_DAYTIME", {})
    _tl_addsong("I'M INVINCIBLE", {"one piece film red", "im invincible", "IM_INVINCIBLE"}, "192", "IM_INVINCIBLE", {"anime/jpop", "movies/tv"})
    _tl_addsong("IM NOT THE ONLY ONE", {"sam smith", "IM_NOT_THE_ONLY_ONE"}, "80", "IM_NOT_THE_ONLY_ONE", {"pop/hiphop", "sad"})
    _tl_addsong("IM STILL STANDING", {"sing", "elton john", "IM_STILL"}, "177", "IM_STILL", {"best", "rock", "movies/tv"})
    _tl_addsong("IMMORTAL", {"playboi carti", "IMMORTAL"}, "60", "IMMORTAL", {"pop/hiphop"})
    _tl_addsong("IMPOSTER SYNDROME", {"IMPOSTER_SYNDROME"}, "120", "IMPOSTER_SYNDROME", {})
    _tl_addsong("IN HELL WE LIVE, LAMENT", {"mili", "limbus company", "IN_HELL_WE_LIVE"}, "65", "IN_HELL_WE_LIVE", {"video games"})
    _tl_addsong("IN THE NAME OF LOVE", {"IN_THE_NAME"}, "134", "IN_THE_NAME", {"pop/hiphop", "electronic", "best", "epic", "beautiful"})
    _tl_addsong("IN THE POOL", {"IN_THE_POOL"}, "120", "IN_THE_POOL", {})
    _tl_addsong("INSANE", {"hazbin hotel", "INSANE"}, "105", "INSANE", {"electronic"})
    _tl_addsong("INSTUPENDO", {"INSTUPENDO"}, "120", "INSTUPENDO", {})
    _tl_addsong("INTERSTELLAR", {"hans zimmer", "cinematic", "movie", "popular", "INTERSTELLAR"}, "104", "INTERSTELLAR", {"epic", "beautiful", "movies/tv"})
    _tl_addsong("INVISIBLE (EDM)", {"ncs", "no copyright sounds", "INVISIBLE"}, "82", "INVISIBLE", {"electronic", "beautiful", "best"})
    _tl_addsong("IRIS OUT", {"IRIS_OUT"}, "120", "IRIS_OUT", {})
    _tl_addsong("ISABELLA'S LULLABY", {"ISABELLAS_LULLABY"}, "112", "ISABELLAS_LULLABY", {"video games"})
    _tl_addsong("ISOLATION", {"limbo", "geometry dash", "gd", "ISOLATION"}, "100", "ISOLATION", {"best", "epic", "video games", "peak"})
    _tl_addsong("IT MEANS EVERYTHING", {"IT_MEANS"}, "96", "IT_MEANS", {"video games", "omori"})
    _tl_addsong("ITS BEEN SO LONG", {"the living tombstone", "five nights at freddys", "fnaf", "ITS_BEEN_SO"}, "96", "ITS_BEEN_SO", {"video games", "electronic"})
    _tl_addsong("ITS JUST A BURNING MEMORY", {"the care taker", "the caretaker", "ITS_JUST_A_BURNING"}, "74", "ITS_JUST_A_BURNING", {"creepy/weirdcore", "memes", "sad"})
    _tl_addsong("ITS RAINING TACOS", {"ITS_RAINING"}, "120", "ITS_RAINING", {"memes"})
    _tl_addsong("IT'S RAINING SOMEWHERE ELSE", {"its raining somewhere else", "toby fox", "ITS_RAINING_SOMEWHERE_ELSE"}, "96", "ITS_RAINING_SOMEWHERE_ELSE", {"video games", "undertale", "new"})
    _tl_addsong("IT'S TV TIME!", {"toby fox", "its tv time", "ITS_TV_TIME"}, "148", "ITS_TV_TIME", {"deltarune", "video games"})
    _tl_addsong("JE TE LAISSERAI DES MOTS", {"JE_TE_LAISSERAI_DES_MOTS"}, "120", "JE_TE_LAISSERAI_DES_MOTS", {})
    _tl_addsong("JEOPARDY THEME", {"JEOPARDY_THEME"}, "120", "JEOPARDY_THEME", {})
    _tl_addsong("JINGLE BELL ROCK", {"JINGLE_BELL_ROCK"}, "120", "JINGLE_BELL_ROCK", {})
    _tl_addsong("JINGLE BELLS", {"JINGLE_BELLS"}, "120", "JINGLE_BELLS", {})
    _tl_addsong("JOCELYN FLORES", {"xxxtentacion", "JOCELYN_FLORES"}, "136", "JOCELYN_FLORES", {"sad", "beautiful"})
    _tl_addsong("JUDAS", {"lady gaga", "JUDAS"}, "130", "JUDAS", {"pop/hiphop"})
    _tl_addsong("JUMPER", {"JUMPER"}, "120", "JUMPER", {})
    _tl_addsong("JUST THE TWO OF US", {"jazz", "JUST_THE_TWO_OF_US"}, "120", "JUST_THE_TWO_OF_US", {})
    _tl_addsong("KAIKAI KITAN", {"KAIKAI_KITAN"}, "120", "KAIKAI_KITAN", {})
    _tl_addsong("KAMADO TANJIRO NO UTA", {"demon slayer", "KAMADO_TANJIRO_NO_UTA"}, "151", "KAMADO_TANJIRO_NO_UTA", {"anime/jpop", "movies/tv"})
    _tl_addsong("KAWAIKUTEGOMEN", {"honeyworks", "sorry for being so cute", "kawaikutegomen"}, "160", "KAWAIKUTEGOMEN", {"anime/jpop", "best"})
    _tl_addsong("KEEP UP (ODETARI)", {"KEEP_UP"}, "135", "KEEP_UP", {"pop/hiphop", "electronic", "new"})
    _tl_addsong("KEROSENE", {"popular", "KEROSENE"}, "116", "KEROSENE", {"electronic"})
    _tl_addsong("KEY", {"c418", "KEY"}, "70", "KEY", {"video games", "minecraft", "beautiful"})
    _tl_addsong("KICK BACK", {"chainsaw man", "KICK_BACK"}, "204", "KICK_BACK", {"movies/tv", "anime/jpop"})
    _tl_addsong("KIDS", {"KIDS"}, "120", "KIDS", {})
    _tl_addsong("KILLSWITCH LULLABY", {"KILLSWITCH_LULLABY"}, "120", "KILLSWITCH_LULLABY", {})
    _tl_addsong("KISS OF DEATH", {"KISS_OF_DEATH"}, "120", "KISS_OF_DEATH", {})
    _tl_addsong("KISS THE RAIN", {"yiruma", "KISS_THE_RAIN"}, "58", "KISS_THE_RAIN", {})
    _tl_addsong("L'S THEME", {"death note", "ls theme", "L"}, "71", "L", {"anime/jpop", "memes", "movies/tv"})
    _tl_addsong("LA CAMPANELLA", {"etude", "hard", "franz liszt", "LA_CAMPANELLA"}, "107", "LA_CAMPANELLA", {"classical", "best", "peak", "beautiful"})
    _tl_addsong("LACRIMOSA (REQUIEM MVT.8)", {"mozart", "noot noot", "LACRIMOSA"}, "64", "LACRIMOSA", {"classical", "memes"})
    _tl_addsong("LALALA", {"bbno", "LALALA"}, "130", "LALALA", {"pop/hiphop"})
    _tl_addsong("L'AMOUR TOUJOURS", {"gigi d'agostino", "gigi dagostino", "LAMOUR_TOUJOURS"}, "160", "LAMOUR_TOUJOURS", {"sad", "memes"})
    _tl_addsong("LAST CHRISTMAS", {"wham", "LAST_CHRISTMAS"}, "120", "LAST_CHRISTMAS", {"pop/hiphop", "best", "new"})
    _tl_addsong("LAST GOODBYE", {"toby fox", "LAST_GOODBYE"}, "180", "LAST_GOODBYE", {"undertale", "video games", "best", "epic", "peak", "new"})
    _tl_addsong("LAVENDER TOWN", {"pokemon", "LAVENDER_TOWN"}, "120", "LAVENDER_TOWN", {"video games", "memes", "creepy/weirdcore"})
    _tl_addsong("LE MONDE", {"LE_MONDE"}, "100", "LE_MONDE", {"best"})
    _tl_addsong("LEAVE THE DOOR OPEN", {"LEAVE_THE_DOOR_OPEN"}, "120", "LEAVE_THE_DOOR_OPEN", {})
    _tl_addsong("REN'AI (レンアイ)", {"rent a girlfriend", "rent-a-girlfriend", "lenai", "renai"}, "131", "LENAI", {"anime/jpop", "movies/tv"})
    _tl_addsong("LET GO", {"LET_GO"}, "120", "LET_GO", {})
    _tl_addsong("LET HER GO", {"passenger", "LET_HER_GO"}, "120", "LET_HER_GO", {"memes", "pop/hiphop"})
    _tl_addsong("LET IT GO", {"elsa", "frozen", "disney", "LET_IT_GO"}, "74", "LET_IT_GO", {"movies/tv", "memes", "best"})
    _tl_addsong("LET IT GO X LET HER GO", {"frozen", "LET_IT_GO_X_LET_HER_GO"}, "120", "LET_IT_GO_X_LET_HER_GO", {})
    _tl_addsong("LET IT HAPPEN", {"tame impala", "LET_IT_HAPPEN"}, "120", "LET_IT_HAPPEN", {"rock", "beautiful"})
    _tl_addsong("LET ME DOWN SLOWLY", {"alec benjamin", "LET_ME_DOWN_SLOWLY"}, "75", "LET_ME_DOWN_SLOWLY", {"sad"})
    _tl_addsong("LET ME LOVE YOU", {"justin bieber", "dj snake", "LET_ME_LOVE"}, "100", "LET_ME_LOVE", {"pop/hiphop", "best", "beautiful"})
    _tl_addsong("LET YOU BREAK MY HEART AGAIN", {"laufey", "LET_YOU_BREAK_MY_HEART_AGAIN"}, "73", "LET_YOU_BREAK_MY_HEART_AGAIN", {"sad"})
    _tl_addsong("LEVAN POLKKA", {"hatsune miku", "vocaloid", "le van", "LEVAN_POLKKA"}, "135", "LEVAN_POLKKA", {"memes"})
    _tl_addsong("LEVELS", {"avicii", "LEVELS"}, "122", "LEVELS", {"electronic", "levels", "best"})
    _tl_addsong("LIEBESTRAUM NO.3", {"franz liszt", "LIEBESTRAUM_NO3"}, "152", "LIEBESTRAUM_NO3", {"classical"})
    _tl_addsong("LIFE WILL CHANGE", {"LIFE_WILL_CHANGE"}, "120", "LIFE_WILL_CHANGE", {})
    _tl_addsong("LIGHT SWITCH", {"charlie puth", "LIGHT_SWITCH"}, "184", "LIGHT_SWITCH", {"pop/hiphop"})
    _tl_addsong("LIGHT'S THEME", {"death note", "lights theme", "LIGHTS"}, "132", "LIGHTS", {"anime/jpop"})
    _tl_addsong("LIKE HIM", {"tyler the creator", "chromakopia", "LIKE_HIM"}, "94", "LIKE_HIM", {"pop/hiphop", "beautiful", "best"})
    _tl_addsong("LIKE HIM (BEST PART)", {"chromakopia", "tyler the creator", "LIKE_HIM_BEST"}, "94", "LIKE_HIM_BEST", {"beautiful", "best", "peak", "pop/hiphop", "epic"})
    _tl_addsong("LIVING MICE", {"c418", "LIVING_MICE"}, "74", "LIVING_MICE", {"video games", "minecraft"})
    _tl_addsong("LOST LIBRARY", {"omori", "LOST_LIBRARY"}, "62", "LOST_LIBRARY", {"video games", "omori"})
    _tl_addsong("LOST UMBRELLA", {"cute depressed", "vocaloid", "inabakumori", "LOST_UMB"}, "133", "LOST_UMB", {"electronic", "anime/jpop"})
    _tl_addsong("LOVE (W2E)", {"wave to earth", "love.", "LOVE"}, "68", "LOVE", {"sad"})
    _tl_addsong("LOVE STORY", {"indila", "LOVE_STORY"}, "180", "LOVE_STORY", {})
    _tl_addsong("LOVELY", {"billie eilish", "khalid", "LOVELY"}, "115", "LOVELY", {"pop/hiphop"})
    _tl_addsong("LOVELY BASTARDS", {"phonk", "LOVELY_B"}, "150", "LOVELY_B", {"memes", "best"})
    _tl_addsong("LOVER IS A DAY", {"cuco", "LOVER_IS_A_DAY"}, "90", "LOVER_IS_A_DAY", {})
    _tl_addsong("LUTHER", {"kendrick lamar", "sza", "GNX", "LUTHER"}, "128", "LUTHER", {"pop/hiphop"})
    _tl_addsong("LUX AETERNA (REQUIEM FOR A DREAM)", {"clint mansell", "LUX_AETERNA"}, "70", "LUX_AETERNA", {"movies/tv"})
    _tl_addsong("MA MEILLEUR ENEMIE", {"stromae", "arcane", "MA_MEILLEUR"}, "178", "MA_MEILLEUR", {"movies/tv"})
    _tl_addsong("M@GICAL CURE! LOVE SHOT!", {"miku", "vocaloid", "hatsune miku", "magical cure", "MAGICAL_CURE"}, "120", "MAGICAL_CURE", {"anime/jpop"})
    _tl_addsong("MANGO MANGO MANGO", {"MANGOMANGOMANGO"}, "110", "MANGOMANGOMANGO", {"peak"})
    _tl_addsong("MARI BOSS FIGHT", {"omori", "MARI_BOSS"}, "169", "MARI_BOSS", {"video games", "omori"})
    _tl_addsong("MARRIED LIFE", {"movie", "up", "MARRIED"}, "83", "MARRIED", {"sad", "movies/tv"})
    _tl_addsong("MARY ON A CROSS", {"MARY_ON"}, "130", "MARY_ON", {"rock"})
    _tl_addsong("MASTER OF PUPPETS", {"metallica", "MASTER_OF_PUPPETS"}, "220", "MASTER_OF_PUPPETS", {"rock"})
    _tl_addsong("MEANINGFUL LOVE", {"MEANINGFUL_LOVE"}, "120", "MEANINGFUL_LOVE", {})
    _tl_addsong("MEGALOVANIA", {"popular", "MEGALOVANIA"}, "120", "MEGALOVANIA", {"video games", "undertale", "memes"})
    _tl_addsong("MERRY CHRISTMAS MR LAWRENCE", {"MERRY_CHRISTMAS_MR_LAWRENCE"}, "120", "MERRY_CHRISTMAS_MR_LAWRENCE", {})
    _tl_addsong("METAMORPHOSIS", {"phonk", "METAMORPH"}, "180", "METAMORPH", {"electronic"})
    _tl_addsong("MICE ON VENUS", {"c418", "MICE_ON"}, "56", "MICE_ON", {"video games", "minecraft", "sad"})
    _tl_addsong("MICHAEL MYERS", {"halloween", "MICHAEL_MYERS"}, "144", "MICHAEL_MYERS", {"memes", "creepy/weirdcore"})
    _tl_addsong("MIDDLE OF THE NIGHT", {"elley duhe", "MIDDLE_OF_THE_NIGHT"}, "93", "MIDDLE_OF_THE_NIGHT", {"pop/hiphop", "epic", "beautiful", "best"})
    _tl_addsong("MII CHANNEL THEME", {"wii", "MII"}, "114", "MII", {"video games", "memes"})
    _tl_addsong("MIKU", {"vocaloid", "MIKU"}, "135", "MIKU", {"anime/jpop"})
    _tl_addsong("MINECRAFT", {"c418", "MINECRAFT"}, "106", "MINECRAFT", {"video games", "minecraft"})
    _tl_addsong("MINGLE (ROUND AND ROUND)", {"squid game", "MINGLE"}, "105", "MINGLE", {"creepy/weirdcore", "movies/tv"})
    _tl_addsong("MONODY", {"ncs", "no copyright sounds", "thefatrat", "MONODY"}, "107", "MONODY", {"electronic", "epic", "best"})
    _tl_addsong("MONTAGEM CORAL", {"phonk", "funk", "MONTAGEM_CORAL"}, "130", "MONTAGEM_CORAL", {"electronic"})
    _tl_addsong("MONTAGEM HIKARI", {"MONTAGEM_HIKARI"}, "120", "MONTAGEM_HIKARI", {})
    _tl_addsong("MONTAGEM TOMADA", {"phonk", "MONTAGEM_TOMADA"}, "120", "MONTAGEM_TOMADA", {"electronic"})
    _tl_addsong("MONTAGEM XONADA", {"MXZI", "phonk", "funk", "MONTAGEM_XONADA"}, "130", "MONTAGEM_XONADA", {"electronic"})
    _tl_addsong("MOOD", {"24kgoldn", "MOOD"}, "91", "MOOD", {"pop/hiphop", "best"})
    _tl_addsong("MOOG CITY", {"c418", "MOOG_CITY"}, "116", "MOOG_CITY", {"video games", "minecraft", "beautiful", "best"})
    _tl_addsong("MOONLIGHT SONATA - FIRST MOVEMENT", {"ludwig van beethoven", "MOONLIGHT"}, "51", "MOONLIGHT", {"classical"})
    _tl_addsong("PEER GYNT OP.46 NO.1 (MORNING MOOD)", {"grow a garden", "MORNING_MOOD"}, "72", "MORNING_MOOD", {"classical", "memes", "video games"})
    _tl_addsong("MRS MAGIC", {"strawberry guy", "MRS_MAGIC"}, "120", "MRS_MAGIC", {"new"})
    _tl_addsong("MULTO", {"ghost", "cup of joe", "MULTO"}, "104", "MULTO", {"pop/hiphop", "best", "new"})
    _tl_addsong("MY CASTLE TOWN", {"toby fox", "MY_CASTLE_TOWN"}, "136", "MY_CASTLE_TOWN", {"video games", "deltarune"})
    _tl_addsong("MY CONFESSION", {"MY_CONFESSION"}, "120", "MY_CONFESSION", {})
    _tl_addsong("MY EYES", {"travis scott", "utopia", "MY_EYES"}, "120", "MY_EYES", {"pop/hiphop", "beautiful", "best"})
    _tl_addsong("MY FEELINGS", {"MY_FEELINGS"}, "120", "MY_FEELINGS", {})
    _tl_addsong("MY HEART WILL GO ON", {"titanic", "celine dion", "MY_HEART_WILL_GO_ON"}, "90", "MY_HEART_WILL_GO_ON", {"sad", "movies/tv", "beautiful", "best"})
    _tl_addsong("MY KIND OF WOMAN", {"mac demarco", "MY_KIND_OF_WOMAN"}, "90", "MY_KIND_OF_WOMAN", {})
    _tl_addsong("MY LOVE MINE ALL MINE", {"mitski", "MY_LOVE_ALL_MINE"}, "57", "MY_LOVE_ALL_MINE", {"sad", "best"})
    _tl_addsong("MY ORDINARY LIFE", {"the living tombstone", "MY_ORDINARY_LIFE"}, "130", "MY_ORDINARY_LIFE", {"electronic"})
    _tl_addsong("MY WAR", {"boku no sensou", "attack on titan", "MY_WAR"}, "140", "MY_WAR", {"movies/tv", "anime/jpop"})
    _tl_addsong("MY WAY", {"frank sinatra", "MY_WAY"}, "80", "MY_WAY", {})
    _tl_addsong("NERVES (FNF VS GARCELLO)", {"friday night funkin", "NERVES"}, "100", "NERVES", {"video games", "new"})
    _tl_addsong("NEVADA", {"NEVADA"}, "120", "NEVADA", {})
    _tl_addsong("NEVER BE ALONE", {"fnaf", "five nights at freddy's", "shadrow", "NEVER_BE_ALONE"}, "105", "NEVER_BE_ALONE", {"video games"})
    _tl_addsong("NEVER MEANT TO BELONG", {"bleach", "NEVER_MEANT"}, "66", "NEVER_MEANT", {"anime/jpop", "movies/tv"})
    _tl_addsong("NEVER SEE ME AGAIN", {"kanye west", "NEVER_SEE_ME_AGAIN"}, "178", "NEVER_SEE_ME_AGAIN", {"pop/hiphop", "best", "new"})
    _tl_addsong("ALL ROADS LEAD TO ROME", {"girlfriends", "new computers", "NEW_COMPUTERS"}, "120", "NEW_COMPUTERS", {"memes", "best", "new"})
    _tl_addsong("NEW HOME", {"NEW_HOME"}, "100", "NEW_HOME", {"new"})
    _tl_addsong("NIGHT DANCER", {"imase", "NIGHT_DANCER"}, "118", "NIGHT_DANCER", {"pop/hiphop", "best"})
    _tl_addsong("NO BATIDAO", {"NO_BATIDAO"}, "120", "NO_BATIDAO", {})
    _tl_addsong("NO SURPRISES", {"radiohead", "NO_SURPRISES"}, "80", "NO_SURPRISES", {"rock", "sad"})
    _tl_addsong("NOCTURNE OP.9 NO.2", {"frederic chopin", "NOCTURNE"}, "62", "NOCTURNE", {"classical", "best"})
    _tl_addsong("NOPE YOUR TOO LATE I ALREADY DIED", {"wifiskeleton", "NOPE_YOUR_TOO_LATE"}, "118", "NOPE_YOUR_TOO_LATE", {"rock", "sad"})
    _tl_addsong("NOT A SLACKER ANYMORE", {"NOT_A_SLACKER"}, "145", "NOT_A_SLACKER", {"video games", "undertale"})
    _tl_addsong("NOT LIKE US", {"kendrick lamar", "drake", "NOT_LIKE_US"}, "101", "NOT_LIKE_US", {"pop/hiphop", "memes"})
    _tl_addsong("NOTHING ELSE MATTERS", {"metallica", "NOTHING_ELSE_MATTERS"}, "75", "NOTHING_ELSE_MATTERS", {"rock", "sad"})
    _tl_addsong("NOTION", {"the rare occasions", "NOTION"}, "160", "NOTION", {"rock", "sad"})
    _tl_addsong("NUKE POWDER", {"NUKE_POWDER"}, "120", "NUKE_POWDER", {})
    _tl_addsong("NUMBERS", {"temporex", "NUMBERS"}, "100", "NUMBERS", {"creepy/weirdcore"})
    _tl_addsong("NYAN CAT", {"NYAN_CAT"}, "140", "NYAN_CAT", {"memes", "best"})
    _tl_addsong("NYEH HEH HEH!", {"papyrus", "NYEH"}, "150", "NYEH", {"video games", "undertale", "best"})
    _tl_addsong("OBLIVION (GRIMES)", {"grimes", "OBLIVION"}, "156", "OBLIVION", {"rock", "beautiful"})
    _tl_addsong("OHAYOU SAYORI", {"OHAYOU_SAYORI"}, "120", "OHAYOU_SAYORI", {})
    _tl_addsong("OKAY EVERYONE", {"OKAY_EVERYONE"}, "120", "OKAY_EVERYONE", {})
    _tl_addsong("OLD DOLL", {"mad father", "OLD_DOLL"}, "100", "OLD_DOLL", {"creepy/weirdcore"})
    _tl_addsong("OLD TOWN ROAD", {"lil nas x", "OLD_TOWN_ROAD"}, "69", "OLD_TOWN_ROAD", {"pop/hiphop", "memes"})
    _tl_addsong("ON MY WAY", {"alan walker", "ncs", "no copyright sounds", "ON_MY_WAY"}, "85", "ON_MY_WAY", {"electronic"})
    _tl_addsong("ONCE UPON A TIME", {"ONCE_UPON"}, "65", "ONCE_UPON", {"video games", "undertale"})
    _tl_addsong("ONCE UPON A DECEMBER", {"ONCE_UPON_A_DECEMBER"}, "120", "ONCE_UPON_A_DECEMBER", {})
    _tl_addsong("ONE DANCE", {"drake", "wizkid", "kyla", "ONE_DANCE"}, "108", "ONE_DANCE", {"pop/hiphop"})
    _tl_addsong("ONE OF THE GIRLS", {"idol", "the weeknd", "ONE_OF_THE_GIRLS"}, "88", "ONE_OF_THE_GIRLS", {"pop/hiphop", "movies/tv", "new"})
    _tl_addsong("ONE SUMMER'S DAY", {"spirited away", "studio ghibli", "joe hisaishi", "one summers day", "ONE_SUMMERS_DAY"}, "78", "ONE_SUMMERS_DAY", {"beautiful", "movies/tv", "anime/jpop"})
    _tl_addsong("ORDER (ULTRAKILL)", {"minos prime bossfight", "ORDER"}, "170", "ORDER", {"video games", "best"})
    _tl_addsong("ORDINARY", {"alex warren", "ORDINARY"}, "168", "ORDINARY", {"pop/hiphop", "sad", "beautiful", "best"})
    _tl_addsong("OVERTAKEN", {"one piece", "OVERTAKEN"}, "105", "OVERTAKEN", {"anime/jpop", "movies/tv"})
    _tl_addsong("PARADISE", {"coldplay", "PARADISE"}, "125", "PARADISE", {"pop/hiphop"})
    _tl_addsong("PASILYO", {"sunkissed lola", "PASILYO"}, "125", "PASILYO", {"new"})
    _tl_addsong("PASSACAGLIA, SUITE NO.7", {"PASSACAGLIA"}, "130", "PASSACAGLIA", {"classical", "beautiful", "best"})
    _tl_addsong("PASSO BEM SOLTO", {"phonk", "PASSO_BEM_SOLTO"}, "120", "PASSO_BEM_SOLTO", {"electronic"})
    _tl_addsong("PAST LIVES", {"PAST_LIVES"}, "110", "PAST_LIVES", {"sad", "beautiful"})
    _tl_addsong("SONATE OP.13 NO.8 (PATHÉTIQUE)", {"ludwig van beethoven", "sonata pathetique", "PATHETIQUE"}, "31", "PATHETIQUE", {"classical"})
    _tl_addsong("PAYPHONE", {"maroon 5", "PAYPHONE"}, "110", "PAYPHONE", {"pop/hiphop", "sad", "best", "beautiful"})
    _tl_addsong("PEACHES", {"jack black", "bowser", "super mario bros", "PEACHES"}, "92", "PEACHES", {"video games", "movies/tv"})
    _tl_addsong("PIANO MAN", {"billy joel", "PIANO_MAN"}, "80", "PIANO_MAN", {})
    _tl_addsong("PIXEL PEEKER POLKA (DON'T TOUCH MY PIZZA)", {"kevin macleod", "dont touch my pizza", "PIXEL_PEEKER_POLKA"}, "145", "PIXEL_PEEKER_POLKA", {"memes"})
    _tl_addsong("PLANT VS ZOMBIES", {"pvz", "PLANT_VS_ZOMBIES"}, "100", "PLANT_VS_ZOMBIES", {"video games", "memes"})
    _tl_addsong("PLAY WITH ME", {"PLAY_WITH_ME"}, "120", "PLAY_WITH_ME", {})
    _tl_addsong("PLEAD (FORSAKEN)", {"roblox forsaken", "last man standing", "c00lkidd", "key after key", "007n7", "PLEAD"}, "120", "PLEAD", {"video games", "electronic"})
    _tl_addsong("POEM PANIC", {"POEM_PANIC"}, "120", "POEM_PANIC", {})
    _tl_addsong("POKEMON MAIN THEME", {"POKEMON"}, "160", "POKEMON", {"video games", "anime/jpop", "movies/tv"})
    _tl_addsong("POKEMON RED AND BLUE", {"POKEMON_RED"}, "180", "POKEMON_RED", {"video games", "anime/jpop", "movies/tv"})
    _tl_addsong("POLARGEIST", {"POLARGEIST"}, "120", "POLARGEIST", {})
    _tl_addsong("POLONAISE IN F SHARP MINOR OP.44", {"frederic chopin", "POLONAISE"}, "100", "POLONAISE", {"classical"})
    _tl_addsong("POSTER BOY", {"POSTER_BOY"}, "120", "POSTER_BOY", {})
    _tl_addsong("PRAYER", {"kendrick lamar", "damn", "PRAYER"}, "147", "PRAYER", {"beautiful", "pop/hiphop"})
    _tl_addsong("BACH - PRELUDE NO.2", {"johann sebastian bach", "PRELUDE_NO2"}, "145", "PRELUDE_NO2", {"classical"})
    _tl_addsong("CHOPIN - PRELUDE OP.28 NO.4", {"frederic chopin", "PRELUDE_OP28"}, "42", "PRELUDE_OP28", {"classical"})
    _tl_addsong("PROPOSE", {"PROPOSE"}, "120", "PROPOSE", {})
    _tl_addsong("RACING INTO THE NIGHT", {"yoasobi", "RACING_INTO"}, "129", "RACING_INTO", {"anime/jpop", "best", "beautiful"})
    _tl_addsong("RAIN", {"tony ann", "RAIN"}, "77", "RAIN", {"beautiful", "best", "epic"})
    _tl_addsong("RANSOM", {"lil tecca", "RANSOM"}, "180", "RANSOM", {"pop/hiphop"})
    _tl_addsong("RAT DANCE", {"chess", "RAT_DANCE"}, "120", "RAT_DANCE", {"memes"})
    _tl_addsong("READY OR NOT (FORSAKEN)", {"c00lkidd chase", "roblox forsaken", "key after key", "READY_OR_NOT"}, "160", "READY_OR_NOT", {"video games", "electronic"})
    _tl_addsong("REFLECTIONS", {"toshifumi hinata", "REFLECTIONS"}, "104", "REFLECTIONS", {"anime/jpop", "best"})
    _tl_addsong("RENAI CIRCULATION", {"bakemonogatari", "RENAI_CIRCULATION"}, "120", "RENAI_CIRCULATION", {"anime/jpop", "memes", "peak", "best"})
    _tl_addsong("RESONANCE", {"home", "RESONANCE"}, "70", "RESONANCE", {"beautiful", "best"})
    _tl_addsong("REVENGE (CREEPER)", {"creeper awww", "tryhardninja", "captainsparklez", "REVENGE"}, "120", "REVENGE", {"video games", "video games", "memes", "best"})
    _tl_addsong("ETUDE OP.10 NO.12 (REVOLUTIONARY)", {"frederic chopin", "REVOLUTIONARY"}, "140", "REVOLUTIONARY", {"classical", "best"})
    _tl_addsong("RIGHTEOUS (MO BEATS)", {"RIGHTEOUS"}, "160", "RIGHTEOUS", {"electronic"})
    _tl_addsong("RIPTIDE", {"vance joy", "RIPTIDE"}, "90", "RIPTIDE", {"pop/hiphop"})
    _tl_addsong("RISE UP", {"thefatrat", "ncs", "no copyright sounds", "RISE_UP"}, "82", "RISE_UP", {"electronic", "epic"})
    _tl_addsong("RISES THE MOON", {"liana flores", "RISES_THE"}, "127", "RISES_THE", {"sad", "beautiful"})
    _tl_addsong("RIVER FLOWS IN YOU", {"RIVER_FLOWS_IN_YOU"}, "137", "RIVER_FLOWS_IN_YOU", {"sad"})
    _tl_addsong("ROBBERY", {"juice wrld", "ROBBERY"}, "80", "ROBBERY", {"pop/hiphop", "sad", "new"})
    _tl_addsong("ROI (VIDEOCLUB)", {"ROI"}, "110", "ROI", {"pop/hiphop", "best", "new"})
    _tl_addsong("RUDE BUSTER", {"toby fox", "RUDE_BUSTER"}, "140", "RUDE_BUSTER", {"deltarune", "video games", "best"})
    _tl_addsong("RUDER BUSTER", {"toby fox", "RUDER_BUSTER"}, "130", "RUDER_BUSTER", {"video games", "deltarune"})
    _tl_addsong("RUE DES TROIS FRERES", {"RUE_DES_TROIS_FRERES"}, "120", "RUE_DES_TROIS_FRERES", {"classical"})
    _tl_addsong("RUINS", {"RUINS"}, "138", "RUINS", {"video games", "undertale"})
    _tl_addsong("RUNAWAY", {"kanye", "popular", "rap", "hip", "RUNAWAY"}, "160", "RUNAWAY", {"pop/hiphop"})
    _tl_addsong("RUNAWAY (AURORA)", {"RUNAWAY_AURORA"}, "90", "RUNAWAY_AURORA", {"sad", "beautiful", "best"})
    _tl_addsong("RUNNING IN THE 90S", {"max coveri", "RUNNING_IN_THE_90S"}, "160", "RUNNING_IN_THE_90S", {"electronic", "memes", "best"})
    _tl_addsong("RUNNING UP THAT HILL", {"stranger things", "RUNNING_UP"}, "108", "RUNNING_UP", {"sad", "pop/hiphop", "movies/tv"})
    _tl_addsong("RUSH C", {"sheet music boss", "RUSH_C"}, "60", "RUSH_C", {})
    _tl_addsong("RUSH E", {"sheet music boss", "RUSH_E"}, "80", "RUSH_E", {"memes"})
    _tl_addsong("RUSH F", {"sheet music boss", "RUSH_F"}, "60", "RUSH_F", {})
    _tl_addsong("RUSH G", {"sheet music boss", "RUSH_G"}, "60", "RUSH_G", {})
    _tl_addsong("RUSH OF LIFE", {"tony ann", "RUSH_OF_LIFE"}, "122", "RUSH_OF_LIFE", {"beautiful", "epic", "best", "peak"})
    _tl_addsong("SAD XXX", {"SAD_XXX"}, "120", "SAD_XXX", {})
    _tl_addsong("SADNESS AND SORROW", {"naruto shippuden", "SADNESS_AND_SORROW"}, "75", "SADNESS_AND_SORROW", {"anime/jpop", "movies/tv"})
    _tl_addsong("SAILOR SONG", {"gianna perez", "SAILOR_SONG"}, "83", "SAILOR_SONG", {"sad"})
    _tl_addsong("SAITAMAS THEME", {"SAITAMAS_THEME"}, "120", "SAITAMAS_THEME", {})
    _tl_addsong("SANS.", {"undertale", "SANS"}, "120", "SANS", {"video games", "undertale", "memes"})
    _tl_addsong("SANTA CLAUS IS COMING", {"SANTA_CLAUS_IS_COMING"}, "120", "SANTA_CLAUS_IS_COMING", {})
    _tl_addsong("SAVE YOUR TEARS", {"weeknd", "SAVE_YOUR"}, "120", "SAVE_YOUR", {"pop/hiphop", "sad"})
    _tl_addsong("SCARLET FOREST", {"toby fox", "SCARLET_FOREST"}, "122", "SCARLET_FOREST", {"video games", "deltarune"})
    _tl_addsong("SEE YOU AGAIN (TYLER THE CREATOR)", {"tyler the creator", "kali urchis", "tyler, the creator", "flower boy", "SEE_YOU_AGAIN"}, "70", "SEE_YOU_AGAIN", {"pop/hiphop", "sad", "beautiful"})
    _tl_addsong("SEE YOU AGAIN (CHARLIE PUTH)", {"charlie puth", "wiz khalifa", "SEE_YOU_AGAIN_CHARLIE"}, "60", "SEE_YOU_AGAIN_CHARLIE", {"pop/hiphop", "sad", "beautiful"})
    _tl_addsong("SCHUBERT - SERENADE", {"franz liszt", "SERENADE"}, "58", "SERENADE", {"classical"})
    _tl_addsong("SHAPE OF YOU", {"ed sheeran", "SHAPE_OF"}, "190", "SHAPE_OF", {"pop/hiphop"})
    _tl_addsong("SHIAWASE (VIP)", {"tidal wave", "geometry dash", "gd", "SHIAWASE"}, "150", "SHIAWASE", {"electronic", "epic", "beautiful", "best"})
    _tl_addsong("SHIKAIRO DAYS", {"my dear friend nokotan", "my deer friend nokotan", "SHIKAIRO"}, "182", "SHIKAIRO", {"anime/jpop", "memes", "best", "movies/tv"})
    _tl_addsong("SHINZOU WO SASEGEYO!", {"attack on titan", "dedicate your heart", "SHINZOU_WO_SASEGEYO"}, "80", "SHINZOU_WO_SASEGEYO", {"anime/jpop", "movies/tv"})
    _tl_addsong("SHOP", {"SHOP"}, "77", "SHOP", {"video games", "undertale"})
    _tl_addsong("SICK OF U", {"boywithuke", "SICK_OF_U"}, "185", "SICK_OF_U", {"sad"})
    _tl_addsong("SILHOUETTE", {"naruto shippuden", "SILHOUETTE"}, "185", "SILHOUETTE", {"anime/jpop", "movies/tv"})
    _tl_addsong("SILLY BILLY (FNF)", {"friday night funkin", "SILLY_BILLY"}, "173", "SILLY_BILLY", {"video games", "new"})
    _tl_addsong("SINKING TOWN", {"SINKING_TOWN"}, "120", "SINKING_TOWN", {})
    _tl_addsong("SKELETAL SHENANIGANS", {"geometry dash", "gd", "SKELETAL_SHENANIGANS"}, "158", "SKELETAL_SHENANIGANS", {"video games", "electronic"})
    _tl_addsong("SKYFALL", {"adele", "SKYFALL"}, "70", "SKYFALL", {"epic", "best"})
    _tl_addsong("SLAY", {"eternxlz", "phonk", "SLAY"}, "120", "SLAY", {"electronic"})
    _tl_addsong("SLOW DANCING IN THE DARK", {"joji", "SLOW_DANCING_IN"}, "89", "SLOW_DANCING_IN", {"sad", "pop/hiphop", "new"})
    _tl_addsong("SNOWFALL", {"oneheart", "SNOWFALL"}, "96", "SNOWFALL", {"beautiful", "sad", "best"})
    _tl_addsong("SNOWMAN", {"christmas", "sia", "SNOWMAN"}, "105", "SNOWMAN", {"pop/hiphop"})
    _tl_addsong("SNOWY", {"SNOWY"}, "120", "SNOWY", {"video games", "undertale"})
    _tl_addsong("SOLAS", {"sad", "SOLAS"}, "120", "SOLAS", {"beautiful"})
    _tl_addsong("SOMEBODY THAT I USED TO KNOW", {"gotye", "SOMEBODY_THAT_I_USED"}, "120", "SOMEBODY_THAT_I_USED", {"pop/hiphop", "sad"})
    _tl_addsong("SOMETHING JUST LIKE THIS", {"the chainsmokers", "SOMETHING_JUST"}, "103", "SOMETHING_JUST", {"pop/hiphop", "sad", "best", "beautiful"})
    _tl_addsong("SONG THAT MIGHT PLAY WHEN YOU FIGHT SANS", {"undertale", "SONG_THAT_MIGHT"}, "120", "SONG_THAT_MIGHT", {"video games", "undertale"})
    _tl_addsong("SOVIET UNION ANTHEM", {"SOVIET_UNION_ANTHEM"}, "80", "SOVIET_UNION_ANTHEM", {"memes"})
    _tl_addsong("SPACE SONG", {"beach house", "SPACE_SONG"}, "75", "SPACE_SONG", {"sad", "pop/hiphop", "beautiful", "epic", "best"})
    _tl_addsong("SPARKLE", {"radwimps", "your name", "kimi no na wa", "SPARKLE"}, "192", "SPARKLE", {"anime/jpop", "best", "beautiful", "movies/tv"})
    _tl_addsong("SPAWN", {"toby fox", "SPAWN"}, "140", "SPAWN", {"deltarune", "video games"})
    _tl_addsong("SPEAR OF JUSTICE", {"SPEAR_OF"}, "130", "SPEAR_OF", {"video games", "undertale", "best"})
    _tl_addsong("SPECIALZ", {"jujutsu kaisen", "jjk", "SPECIALZ"}, "117", "SPECIALZ", {"movies/tv", "anime/jpop"})
    _tl_addsong("SPECTRE", {"alan walker", "ncs", "no copyright sounds", "smurf cat", "SPECTRE"}, "128", "SPECTRE", {"electronic", "memes", "beautiful", "best"})
    _tl_addsong("AT THE SPEED OF LIGHT", {"geometry dash", "gd", "SPEED_OF"}, "162", "SPEED_OF", {"video games", "electronic", "epic", "best", "peak"})
    _tl_addsong("SPIDER DANCE", {"muffet", "toby fox", "SPIDER_DANCE"}, "115", "SPIDER_DANCE", {"video games", "undertale"})
    _tl_addsong("SPOOKY SCARY SKELETONS", {"halloween", "SPOOKY_SCARY_SKELETONS"}, "225", "SPOOKY_SCARY_SKELETONS", {"creepy/weirdcore", "best"})
    _tl_addsong("THE 4 SEASONS - SPRING", {"the 4 seasons", "vivaldi", "the four seasons", "SPRING"}, "100", "SPRING", {"classical", "video games", "memes", "best"})
    _tl_addsong("STAY", {"justin bieber", "kid laroi", "STAY"}, "85", "STAY", {"pop/hiphop"})
    _tl_addsong("STAYIN' ALIVE", {"the bee gees", "the bee gess", "STAYIN_ALIVE"}, "103", "STAYIN_ALIVE", {"pop/hiphop", "rock", "movies/tv"})
    _tl_addsong("STEREO HEARTS", {"gym class heroes", "adam levine", "STEREO_HEARTS"}, "96", "STEREO_HEARTS", {"pop/hiphop", "best"})
    _tl_addsong("STEREO LOVE", {"STEREO_LOVE"}, "120", "STEREO_LOVE", {})
    _tl_addsong("STEREO MADNESS", {"geometry dash", "gd", "STEREO_MADNESS"}, "160", "STEREO_MADNESS", {"video games", "electronic"})
    _tl_addsong("STILL D.R.E.", {"snoop dogg", "STILL_DRE"}, "92", "STILL_DRE", {"pop/hiphop", "best"})
    _tl_addsong("STRANGER THINGS", {"STRANGER_THINGS"}, "80", "STRANGER_THINGS", {"movies/tv"})
    _tl_addsong("STRANGERS", {"kenya grace", "STRANGERS"}, "170", "STRANGERS", {"pop/hiphop", "sad", "best", "beautiful"})
    _tl_addsong("STRESSED OUT", {"twenty one pilots", "21 pilots", "heathens", "STRESSED_OUT"}, "170", "STRESSED_OUT", {"pop/hiphop", "best"})
    _tl_addsong("SUBWOOFER LULLABY", {"c418", "SUBWOOFER"}, "76", "SUBWOOFER", {"video games", "minecraft"})
    _tl_addsong("SUCCESSION THEME", {"SUCCESSION_THEME"}, "120", "SUCCESSION_THEME", {})
    _tl_addsong("DANCE OF THE SUGAR PLUM FAIRY", {"christmas", "hard", "SUGAR_PLUM"}, "70", "SUGAR_PLUM", {"classical"})
    _tl_addsong("THE 4 SEASONS - SUMMER", {"the 4 seasons", "vivaldi", "the four seasons", "SUMMER"}, "150", "SUMMER", {"classical", "epic", "best", "beautiful", "peak"})
    _tl_addsong("SUNFLOWER", {"spider man", "post malone", "SUNFLOWER"}, "90", "SUNFLOWER", {"pop/hiphop", "beautiful", "best", "movies/tv"})
    _tl_addsong("SUPER IDOL", {"SUPER_IDOL"}, "136", "SUPER_IDOL", {"memes"})
    _tl_addsong("SUPER MARIO BROS", {"SUPER_MARIOS"}, "180", "SUPER_MARIOS", {"video games", "memes"})
    _tl_addsong("SUPER SHY", {"SUPER_SHY"}, "120", "SUPER_SHY", {})
    _tl_addsong("SUPER SMASH BROS. ULTIMATE", {"super smash bros", "SUPER_SMASH_BROS"}, "145", "SUPER_SMASH_BROS", {"video games", "new"})
    _tl_addsong("I WILL SURVIVE", {"SURVIVE"}, "80", "SURVIVE", {"pop/hiphop", "best"})
    _tl_addsong("SUZUME", {"radwimps", "SUZUME"}, "78", "SUZUME", {"anime/jpop", "best", "beautiful", "movies/tv"})
    _tl_addsong("SWAN LAKE", {"tchaikovsky", "SWAN_LAKE"}, "100", "SWAN_LAKE", {"classical"})
    _tl_addsong("SWEATER WEATHER", {"the neighbourhood", "love", "popular", "SWEATER_WEATHER"}, "124", "SWEATER_WEATHER", {"sad"})
    _tl_addsong("SWEDEN", {"c418", "SWEDEN"}, "44", "SWEDEN", {"video games", "minecraft"})
    _tl_addsong("SWEET DREAMS", {"sweet dreams are made of this", "SWEET_DREAMS"}, "125", "SWEET_DREAMS", {"pop/hiphop", "best", "new"})
    _tl_addsong("SWEETLY", {"SWEETLY"}, "120", "SWEETLY", {})
    _tl_addsong("SWIMMING", {"flawed mangoes", "dramamime", "SWIMMING"}, "165", "SWIMMING", {"beautiful", "best"})
    _tl_addsong("SYMPHONY NO.5", {"ludwig van beethoven", "5th symphony", "fifth symphony", "SYMPHONY_NO5"}, "120", "SYMPHONY_NO5", {"classical"})
    _tl_addsong("TAKE FIVE", {"dave brubeck", "jazz", "TAKE_FIVE"}, "166", "TAKE_FIVE", {})
    _tl_addsong("TAKE ME BACK HOME", {"TAKE_ME_BACK_HOME"}, "120", "TAKE_ME_BACK_HOME", {})
    _tl_addsong("TAKE ON ME", {"a-ha", "TAKE_ON_ME"}, "169", "TAKE_ON_ME", {"pop/hiphop"})
    _tl_addsong("TEK IT", {"cafune", "TEK_IT"}, "147", "TEK_IT", {})
    _tl_addsong("TEST DRIVE", {"how to train your dragon", "john powell", "TEST_DRIVE"}, "120", "TEST_DRIVE", {"epic", "movies/tv"})
    _tl_addsong("TETORIS", {"TETORIS"}, "120", "TETORIS", {})
    _tl_addsong("THANG DIEN", {"THANG_DIEN"}, "120", "THANG_DIEN", {})
    _tl_addsong("THATS WHAT I WANT", {"lil nas x", "THATS_WHAT_I_WANT"}, "85", "THATS_WHAT_I_WANT", {"pop/hiphop"})
    _tl_addsong("THE ABYSS", {"THE_ABYSS"}, "120", "THE_ABYSS", {})
    _tl_addsong("THE AMAZING DIGITAL CIRCUS", {"pomni", "THE_AMAZING_DIGITAL"}, "110", "THE_AMAZING_DIGITAL", {"best", "movies/tv"})
    _tl_addsong("THE BEGINNING", {"flawed mangoes", "THE_BEGINNING"}, "150", "THE_BEGINNING", {"beautiful"})
    _tl_addsong("THE BENONI", {"THE_BEN"}, "180", "THE_BEN", {"classical", "epic", "best"})
    _tl_addsong("THE BLUE DANUBE", {"squid game", "THE_BLUE_DANUBE"}, "120", "THE_BLUE_DANUBE", {"classical"})
    _tl_addsong("THE ECSTASY OF GOLD", {"the good, the bad and the ugly", "the good the bad and the ugly", "THE_ECSTASY_OF_GOLD"}, "85", "THE_ECSTASY_OF_GOLD", {"movies/tv", "epic", "beautiful"})
    _tl_addsong("THE ENTERTAINER", {"THE_ENTERTAINER"}, "60", "THE_ENTERTAINER", {"memes", "best"})
    _tl_addsong("THE GREAT FAIRY FOUNTAIN", {"zelda", "the legend of zelda", "THE_GREAT_FAIRY"}, "80", "THE_GREAT_FAIRY", {"video games"})
    _tl_addsong("THE LEGEND", {"toby fox", "THE_LEGEND"}, "110", "THE_LEGEND", {"video games", "deltarune"})
    _tl_addsong("THE NIGHTS", {"avicii", "THE_NIGHTS"}, "128", "THE_NIGHTS", {"pop/hiphop", "electronic", "epic"})
    _tl_addsong("THE REAL SLIM SHADY", {"eminem", "THE_REAL_SLIM_SHADY"}, "105", "THE_REAL_SLIM_SHADY", {"pop/hiphop", "new"})
    _tl_addsong("THE SEARCH", {"nf", "THE_SEARCH"}, "120", "THE_SEARCH", {"pop/hiphop", "epic", "beautiful", "best"})
    _tl_addsong("THE SLAUGHTER CONTINUES", {"undertale last breath", "last breath", "THE_SLAUGHTER_CONT"}, "150", "THE_SLAUGHTER_CONT", {"video games", "undertale"})
    _tl_addsong("THE WINNER TAKES IT ALL", {"THE_WINNER_TAKES_IT_ALL"}, "120", "THE_WINNER_TAKES_IT_ALL", {})
    _tl_addsong("THE WORLD", {"death note", "THE_WORLD"}, "96", "THE_WORLD", {"anime/jpop", "rock", "movies/tv"})
    _tl_addsong("THE WORLD REVOLVING", {"toby fox", "THE_WORLD_REVOLVING"}, "190", "THE_WORLD_REVOLVING", {"deltarune", "video games", "best"})
    _tl_addsong("THE X FILES", {"THE_X_FILES"}, "120", "THE_X_FILES", {})
    _tl_addsong("THEORY OF EVERYTHING", {"THEORY_OF_EVERYTHING"}, "120", "THEORY_OF_EVERYTHING", {})
    _tl_addsong("THICK OF IT", {"nigga", "ksi", "shit", "popular", "THICK_OF_IT"}, "146", "THICK_OF_IT", {"memes"})
    _tl_addsong("THIS IS HALLOWEEN", {"THIS_IS_HALLOWEEN"}, "160", "THIS_IS_HALLOWEEN", {"creepy/weirdcore"})
    _tl_addsong("THIS IS HOME", {"THIS_IS_HOME"}, "120", "THIS_IS_HOME", {})
    _tl_addsong("THIS IS WHAT FALLING IN LOVE FEELS LIKE", {"jvke", "THIS_IS_WHAT_FALLING_IN_LOVE"}, "80", "THIS_IS_WHAT_FALLING_IN_LOVE", {"beautiful", "pop/hiphop"})
    _tl_addsong("THIS IS WHAT HEARTBREAK FEELS LIKE", {"jvke", "golden hour", "THIS_IS_WHAT_HEARTBREAK"}, "50", "THIS_IS_WHAT_HEARTBREAK", {"sad", "pop/hiphop"})
    _tl_addsong("THIS IS WHAT SPACE FEELS LIKE", {"jvke", "THIS_IS_WHAT_SPACE"}, "130", "THIS_IS_WHAT_SPACE", {"beautiful", "pop/hiphop", "new"})
    _tl_addsong("THIS IS WHAT WINTER FEELS LIKE", {"jvke", "golden hour", "THIS_IS_WHAT_WINTER"}, "115", "THIS_IS_WHAT_WINTER", {"beautiful", "pop/hiphop", "best"})
    _tl_addsong("THROUGH PATCHES OF VIOLET", {"THROUGH_PATCHES_OF_VIOLET"}, "120", "THROUGH_PATCHES_OF_VIOLET", {})
    _tl_addsong("THUNDERSTRUCK", {"THUNDERSTRUCK"}, "120", "THUNDERSTRUCK", {})
    _tl_addsong("TICKING", {"TICKING"}, "77", "TICKING", {"epic", "best", "beautiful"})
    _tl_addsong("TIME", {"hans zimmer", "inception", "TIME"}, "60", "TIME", {"movies/tv", "beautiful", "epic", "new"})
    _tl_addsong("TIME BACK", {"TIME_BACK"}, "120", "TIME_BACK", {"movies/tv"})
    _tl_addsong("TIME FLOWS EVER ONWARD", {"frieren", "sousou no frieren", "frieren: beyond journey's end", "frieren beyond journeys end", "TIME_FLOWS_EVER_ONWARD"}, "100", "TIME_FLOWS_EVER_ONWARD", {"movies/tv", "anime/jpop"})
    _tl_addsong("TIMELESS", {"the weeknd", "the weekend", "playboi carti", "TIMELESS"}, "120", "TIMELESS", {"pop/hiphop"})
    _tl_addsong("TOOK HER TO THE O", {"TOOK_HER_TO_THE_O"}, "120", "TOOK_HER_TO_THE_O", {})
    _tl_addsong("ETUDE OP.10 NO.4 (TORRENT)", {"frederic chopin", "TORRENT"}, "190", "TORRENT", {"classical", "epic", "best", "peak"})
    _tl_addsong("TOXIC (BOYWITHUKE)", {"TOXIC"}, "180", "TOXIC", {"sad", "pop/hiphop"})
    _tl_addsong("TRANSCEDENTAL ETUDE 4", {"TRANSCEDENTAL_ETUDE_4"}, "120", "TRANSCEDENTAL_ETUDE_4", {})
    _tl_addsong("TRAP ROYALTY", {"fetty wap", "TRAP_R"}, "151", "TRAP_R", {"memes", "epic", "best", "beautiful"})
    _tl_addsong("TREACHERY", {"TREACHERY"}, "120", "TREACHERY", {})
    _tl_addsong("TURKISH MARCH", {"mozart", "rondo alla turca", "TURKISH"}, "92", "TURKISH", {"classical"})
    _tl_addsong("UNDERSTAND", {"boywithuke", "UNDERSTAND"}, "206", "UNDERSTAND", {"sad"})
    _tl_addsong("UNDERTALE", {"UNDERTALE"}, "100", "UNDERTALE", {"video games", "undertale", "best", "epic"})
    _tl_addsong("UNDERWATER PROM QUEENS", {"omori", "UNDERWATER"}, "160", "UNDERWATER", {"video games", "omori"})
    _tl_addsong("UNITY", {"thefatrat", "ncs", "no copyright sounds", "UNITY"}, "110", "UNITY", {"electronic", "best"})
    _tl_addsong("UNRAVEL", {"tokyo ghoul", "UNRAVEL"}, "135", "UNRAVEL", {"anime/jpop", "beautiful", "movies/tv"})
    _tl_addsong("UNRAVEL (ANIMENZ ARR.)", {"tokyo ghoul", "animenz", "unravel epic", "UNRAVEL_EPIC"}, "132", "UNRAVEL_EPIC", {"epic", "best", "beautiful", "peak", "movies/tv"})
    _tl_addsong("UNSTOPPABLE", {"sia", "UNSTOPPABLE"}, "85", "UNSTOPPABLE", {"pop/hiphop", "best"})
    _tl_addsong("UNTIL I FOUND YOU", {"stephen sanchez", "UNTIL_I_FOUND_YOU"}, "101", "UNTIL_I_FOUND_YOU", {"pop/hiphop", "sad", "beautiful", "best"})
    _tl_addsong("UNTITLED", {"oobja main theme", "cooked", "UNTITLED"}, "25", "UNTITLED", {"video games", "memes", "sad", "creepy/weirdcore"})
    _tl_addsong("UWA!! SO TEMPERATE♫", {"toby fox", "UWA_SO_TEMPERATE"}, "130", "UWA_SO_TEMPERATE", {"undertale", "video games"})
    _tl_addsong("VAMPIRE", {"olivia rodrigo", "VAMPIRE"}, "135", "VAMPIRE", {"pop/hiphop", "sad", "best"})
    _tl_addsong("VAN GOGH", {"VAN_GOGH"}, "110", "VAN_GOGH", {"classical", "beautiful", "new"})
    _tl_addsong("VICTORY", {"VICTORY"}, "120", "VICTORY", {})
    _tl_addsong("VICTORY BEST PART", {"VICTORY_BEST_PART"}, "120", "VICTORY_BEST_PART", {})
    _tl_addsong("VIENNA", {"billy joel", "VIENNA"}, "120", "VIENNA", {})
    _tl_addsong("VIVA LA VIDA", {"coldplay", "VIVA_LA_VIDA"}, "138", "VIVA_LA_VIDA", {"epic", "beautiful", "best", "peak"})
    _tl_addsong("VOILA", {"VOILA"}, "120", "VOILA", {})
    _tl_addsong("WAITING FOR LOVE", {"avicii", "WAITING_FOR"}, "129", "WAITING_FOR", {"pop/hiphop", "electronic", "best", "epic"})
    _tl_addsong("WAKE ME UP", {"avicii", "WAKE_ME"}, "110", "WAKE_ME", {"pop/hiphop", "electronic"})
    _tl_addsong("CHOPIN - WALTZ OP.64 NO.2", {"frederic chopin", "WALTZ_IN_C_MINOR"}, "120", "WALTZ_IN_C_MINOR", {"classical"})
    _tl_addsong("WASHING MACHINE HEART", {"mitski", "WASHING"}, "114", "WASHING", {"sad", "beautiful", "best"})
    _tl_addsong("WATERFALL", {"toby fox", "WATERFALL"}, "70", "WATERFALL", {"video games", "undertale"})
    _tl_addsong("ONE PIECE - WE ARE!", {"WE_ARE"}, "168", "WE_ARE", {"anime/jpop", "movies/tv"})
    _tl_addsong("WE ARE NUMBER ONE", {"WE_ARE_NUMBER_ON"}, "168", "WE_ARE_NUMBER_ON", {"memes", "new"})
    _tl_addsong("WE DONT TALK ABOUT BRUNO", {"encanto", "WE_DONT"}, "103", "WE_DONT", {})
    _tl_addsong("WE NOT LIKE YOU", {"nettspend", "WE_NOT_LIKE_U"}, "155", "WE_NOT_LIKE_U", {"pop/hiphop", "memes", "new"})
    _tl_addsong("WE WERE ANGELS", {"dragon ball z", "WE_WERE_ANGELS"}, "148", "WE_WERE_ANGELS", {"anime/jpop", "movies/tv"})
    _tl_addsong("WE WISH YOU A MERRY", {"WE_WISH_YOU_A_MERRY"}, "120", "WE_WISH_YOU_A_MERRY", {})
    _tl_addsong("WEDDING MARCH", {"wedding", "WEDDING_MARCH"}, "115", "WEDDING_MARCH", {"memes", "beautiful", "classical"})
    _tl_addsong("WET HANDS", {"c418", "WET_HANDS"}, "74", "WET_HANDS", {"video games", "minecraft", "beautiful"})
    _tl_addsong("WHAT IS LOVE", {"haddaway", "WHAT_IS_LOVE"}, "120", "WHAT_IS_LOVE", {"pop/hiphop", "electronic"})
    _tl_addsong("MOONLIGHT SONATA - THIRD MOVEMENT", {"ludwig van beethoven", "WHAT_THE_FUCKK"}, "163", "WHAT_THE_FUCKK", {"classical", "best", "peak"})
    _tl_addsong("WHAT WAS I MADE FOR", {"billie eilish", "WHAT_WAS_I_MADE_FOR"}, "80", "WHAT_WAS_I_MADE_FOR", {"movies/tv", "pop/hiphop"})
    _tl_addsong("WHEN I MET YOU", {"apo hiking society", "WHEN_I_MET_YOU"}, "70", "WHEN_I_MET_YOU", {})
    _tl_addsong("WHERE OUR BLUE IS", {"tatsuya kitani", "jjk", "jujutsu kaisen", "WHERE_OUR_BLUE_IS"}, "152", "WHERE_OUR_BLUE_IS", {"anime/jpop", "movies/tv"})
    _tl_addsong("WHERE WE PLAYED", {"omori", "WHERE_WE"}, "96", "WHERE_WE", {"video games", "omori"})
    _tl_addsong("WHY DID I SAY OKIE-DOKIE", {"doki doki literature club", "ddlc", "WHY_DID_I_SAY"}, "113", "WHY_DID_I_SAY", {})
    _tl_addsong("WIEGE", {"alien stage", "WIEGE"}, "75", "WIEGE", {"movies/tv"})
    _tl_addsong("WII SPORTS TITLE THEME", {"wii sports", "nintendo", "WII_SPORTS_TITLE"}, "115", "WII_SPORTS_TITLE", {"video games", "memes", "epic"})
    _tl_addsong("THE 4 SEASONS - WINTER", {"the 4 seasons", "vivaldi", "the four seasons", "WINTER"}, "136", "WINTER", {"classical", "best", "beautiful", "epic", "peak"})
    _tl_addsong("ETUDE OP.25 NO.11 (WINTER WIND)", {"frederic chopin", "WINTER_WIND"}, "125", "WINTER_WIND", {"classical"})
    _tl_addsong("WORLDS END VALENTINE", {"omori", "WORLDS_END"}, "152", "WORLDS_END", {"video games", "omori", "best"})
    _tl_addsong("XO TOUR LLIF3", {"lil uzi vert", "XO_TOUR"}, "142", "XO_TOUR", {"pop/hiphop", "sad"})
    _tl_addsong("XSTEP", {"XSTEP"}, "120", "XSTEP", {})
    _tl_addsong("YLANG YLANG", {"YLANG_YLANG"}, "71", "YLANG_YLANG", {"sad", "beautiful", "memes", "best", "new"})
    _tl_addsong("YOUNG GIRL A", {"siinamota", "vocaloid", "YOUNG_GIRL_A"}, "130", "YOUNG_GIRL_A", {"anime/jpop", "sad", "beautiful", "best"})
    _tl_addsong("YOUNG GIRL A", {"siinamota", "vocaloid", "YOUNG_GIRL_A_2"}, "130", "YOUNG_GIRL_A_2", {"anime/jpop", "sad", "epic", "best", "beautiful", "peak"})
    _tl_addsong("YOUR GAZE, CREPUSCULAR", {"the fragrant flower blooms with dignity", "Manazashi wa Hikari", "YOUR_GAZE"}, "144", "YOUR_GAZE", {"anime/jpop", "movies/tv", "beautiful", "best"})
    _tl_addsong("YOUR LOVE IS MY DRUG", {"YOUR_LOVE_IS_MY_DRUG"}, "120", "YOUR_LOVE_IS_MY_DRUG", {})
    _tl_addsong("YOUR POWER", {"billie eilish", "YOUR_POWER"}, "130", "YOUR_POWER", {"pop/hiphop", "new"})
    _tl_addsong("YOUR REALITY", {"ddlc", "doki", "YOUR_REALITY"}, "105", "YOUR_REALITY", {"video games", "beautiful", "best"})
    _tl_addsong("YUUSHA/THE BRAVE (勇者)", {"yoasobi", "frieren", "sousou no frieren", "frieren: beyond journey's end", "frieren beyond journeys end", "YUUSHA"}, "208", "YUUSHA", {"anime/jpop"})
    _tl_addsong("ZOMBIE", {"the cranberries", "ZOMBIE"}, "164", "ZOMBIE", {"rock"})
]]

-- Parchea el MAIN limpio.
local patched = source
if INCLUDE_ALL_SONGS then
    local header = [[
local songs = {}
local function _tl_addsong(name, alias, bpm, url, cat)
    table.insert(songs, {button = newSongButton(name, alias), bpm = bpm, var = false, url = url, cat = cat})
end
]]
    local replacement = (header .. SONG_CALLS):gsub("%%", "%%%%")
    patched = patched:gsub("local songs = %b{}", replacement, 1)

    -- Anade la categoria 'levels' (presente en la metadata historica).
    patched = patched:gsub(
        "local categories = %b{}",
        'local categories = {"new","peak","best","epic","beautiful","video games","movies/tv","memes","classical","pop/hiphop","anime/jpop","sad","seasonal","electronic","phonk/funk","rock","creepy/weirdcore","undertale","deltarune","minecraft","nintendo","geometry dash","omori","ddlc","levels"}',
        1
    )
end

-- Evita que "cambiar idioma" recargue el MAIN ofuscado.
patched = patched:gsub(
    'loadstring%(game:HttpGet%("https://hellohellohell0%.com/talentless%-raw/MAIN%.lua", true%)%)',
    "loadstring(_G.TL_NOKEY_SRC)()"
)

_G.TL_NOKEY_SRC = patched

-- Ejecuta la version sin key.
local ok, err = pcall(function()
    loadstring(patched)()
end)

if not ok then
    warn("[TL-NOKEY] Error al ejecutar TALENTLESS: " .. tostring(err))
else
    print("[TL-NOKEY] TALENTLESS sin key cargado.")
end